### ISSUE TITLE
Unable to import 'collections.abc'  using python 3.13.1

### ISSUE THREAD

**Issue by Christian-B** [pylint-dev/pylint#10112] opened 2024-12-06 12:56 UTC
### Bug description

```python
import collections.abc
```

### Configuration

```ini

```

### Command used

```shell
We use a complex github actions but notice the change when python updated to 3.13.1
using pylint-3.3.2
```

### Pylint output

```python
************* Module spinn_utilities.checker
spinn_utilities/checker.py:1:0: C0304: Final newline missing (missing-final-newline)
spinn_utilities/checker.py:1:0: E0401: Unable to import 'collections.abc' (import-error)
spinn_utilities/checker.py:1:0: W0611: Unused import collections.abc (unused-import)
```

### Expected behavior

Not seeing the Unable to import 'collections.abc' (import-error)

Other messages are due to the tiny example

likely due to
https://github.com/python/cpython/commit/d46d291bd390027811937bbf5af2e2600b8398a9

### Pylint version

```shell
Python 3.13.1

Did not happen with 
Python 3.13.0
```

### OS / Environment

tested with github actions using 
Ubuntu
  22.0[4](https://github.com/SpiNNakerManchester/SpiNNUtils/actions/runs/12199055579/job/34032094669#step:1:4).5
  LTS

### Additional dependencies

```python

```

**Comment by jacobtylerwalls** [comment] 2024-12-07 02:08
Thanks, we'll jump on this 👍

**Comment by jacobtylerwalls** [comment] 2024-12-08 11:31
Reopening to keep visibility until we bump astroid later today.

**Comment by jacobtylerwalls** [comment] 2024-12-08 14:39
Polling other contributors, can anyone reproduce this locally? @zenlyj @mbyrnepr2

**Comment by mbyrnepr2** [comment] 2024-12-09 11:38
LGTM @jacobtylerwalls 

```python
(venv3131) markbyrne@Marks-MacBook-Air-2 programming % python -m pylint --version
pylint 4.0.0-dev0
astroid 3.3.6
Python 3.13.1 (v3.13.1:06714517797, Dec  3 2024, 14:00:22) [Clang 15.0.0 (clang-1500.3.9.4)]
(venv3131) markbyrne@Marks-MacBook-Air-2 programming % cat x.py
import collections.abc
(venv3131) markbyrne@Marks-MacBook-Air-2 programming % python -V
Python 3.13.1
(venv3131) markbyrne@Marks-MacBook-Air-2 programming % python -m pylint x.py
************* Module x
x.py:1:0: C0114: Missing module docstring (missing-module-docstring)
x.py:1:0: W0611: Unused import collections.abc (unused-import)

------------------------------------------------------------------
Your code has been rated at 0.00/10 (previous run: 0.00/10, +0.00)

(venv3131) markbyrne@Marks-MacBook-Air-2 programming % 
```

**Comment by zenlyj** [comment] 2024-12-09 12:09
reproducible on my end as well

```
import.py:1:0: E0401: Unable to import 'collections.abc' (import-error)
import.py:1:0: W0611: Unused import collections.abc (unused-import)
```

with the following:
```
pylint 4.0.0-dev0 (latest main)
astroid 3.3.5
Python 3.13.1
```

**Comment by jacobtylerwalls** [comment] 2024-12-09 13:23
Thanks. By chance is anyone testing on linux locally? If it wasn't clear, I have doubts that astroid 3.3.6 fixed anything.

**Comment by Pierre-Sassoulas** [comment] 2024-12-09 13:35
I have linux but didn't find an easy way to install 3.13.1 yet.

**Comment by Torom** [comment] 2024-12-09 17:37
Here you can see my failed GitHub action due to the error: https://github.com/Torom/BotLi/actions/runs/12241011421/job/34145142509

```
Python 3.13.1
astroid-3.3.6
dill-0.3.9
isort-5.13.2
mccabe-0.7.0
platformdirs-4.3.6
pylint-3.3.2
tomlkit-0.13.2
```

**Comment by Pierre-Sassoulas** [comment] 2024-12-09 19:23
Thank you @Torom ! I managed to fix my issue with ``uv self update`` (then 3.13.1 is available)

**Comment by Pierre-Sassoulas** [comment] 2024-12-09 22:48
All right, I can reproduce the ``collections.abc`` issue locally. On main:
```
pylint 4.0.0-dev0
astroid 3.3.5
Python 3.13.1 (main, Dec  6 2024, 18:40:43) [Clang 18.1.8 ]
```
Switching to ``dependabot/pip/astroid-3.3.6`` I also reproduce with:
```
pylint 4.0.0-dev0
astroid 3.3.6
Python 3.13.1 (main, Dec  6 2024, 18:40:43) [Clang 18.1.8 ]
```
I'm wondering if the race condition fixed in the initial issue is bypassing our astroid brain mechanism, but this is just intuition. Let me know if there's any particular test/debug I could do Jacob, I'll be able to dig into this in ~= 20 hours.

**Comment by jacobtylerwalls** [comment] 2024-12-10 00:12
Wonderful. I'd sniff around `do_import_module()`, maybe see if turning `use_cache` off helps? And also play with reverting the 3.3.6 change.

**Comment by jacobtylerwalls** [comment] 2024-12-10 22:30
Watch out, did you test `collection.abc` not `collections.abc`?

**Comment by Pierre-Sassoulas** [comment] 2024-12-10 22:42
*heavy sigh* hmm.. yes 😄 But basically the same thing is happening with the correct import..![Image](https://github.com/user-attachments/assets/1f696b45-545e-4987-be04-d10b4f77b11a)

**Comment by andy-maier** [comment] 2024-12-12 07:03
Just in case it helps, here is when it happens for one of our projects, all from https://github.com/zhmcclient/python-zhmcclient/actions/runs/12216477009

```
OS                          Python  pylint  astroid  Issue occurs 
-----------------------------------------------------------------
Ubuntu 22.04.5              3.13.1  3.3.2   3.3.5    Yes           
MacOS 14.7.1                3.13.0  3.3.2   3.3.5    No            
Windows Server 10.0.20348   3.13.1  3.3.2   3.3.5    Yes           
```

On my local macOS, I have Python 3.13.0 (latest from Homebrew) so I cannot reproduce it there.

**Comment by andy-maier** [comment] 2024-12-12 07:55
The change in Python 3.13.1 is that `collections.abc` no longer has a module file `abc.py` like it did up to 3.13.0 (e.g. https://github.com/python/cpython/blob/v3.13.0/Lib/collections/abc.py), but creates the module dynamically: https://github.com/python/cpython/blob/v3.13.1/Lib/collections/__init__.py#L29

**Comment by DanielNoord** [comment] 2024-12-18 23:41
Fix for `astroid` in https://github.com/pylint-dev/astroid/pull/2657. Please review if you have the time.

If anybody who is running into this issue could try to test out the `astroid` version of that branch to confirm that it fixes the issues that would be awesome. At least on my machine it does reproduce and with that fix it doesn't.

**Closed** 2024-12-24 00:38 UTC
Labels: Bug :beetle:, High priority

**Comment by emily-ocasio** [comment] 2025-01-08 21:05
Using pylint 3.3.3 and astroid 3.3.8 I am still getting issue Unable to import 'collections.abc'  First noticed today when upgrading to python 3.13.1

**Comment by Christian-B** [comment] 2025-01-09 06:54
We have  enabled the github action which found this issue.
It used the latest version of all dependencies including  astroid-3.3.8

Pylint works fine!
