### ISSUE TITLE
Pylint crash on a simple program

### ISSUE THREAD

**Issue by vdanjean** [pylint-dev/pylint#9552] opened 2024-04-17 09:23 UTC
The program is a collection of implementation written by students for a simple problem. Functions are not really written in a pythonic way but it is code that runs correctly that should not make pylint crashing.

### Bug description

When parsing the following ``a.py``:

```python
#!/usr/bin/env python3
"""
Corrections possible pour prettyPrint
"""

def pretty_print1(tab: list[int]):
    """
    Écrit les nombres du tableau `tab` avec 4 chiffres
    (avec éventuellement des 0 devant)

    Les nombres doivent être positifs et de 4 chiffres au plus
    >>> pretty_print1([7, 800, 32, 4500, 12345, -12])
    0007
    0800
    0032
    4500
    12345
    000-12

    """
    for val in tab:
        if val < 10:
            print("000" + str(val))
        elif val < 100:
            print("00" + str(val))
        elif val < 1000:
            print("0" + str(val))
        else:
            print(str(val))

def pretty_print2(tab: list[int]):
    """
    Écrit les nombres du tableau `tab` avec 4 chiffres
    (avec éventuellement des 0 devant)

    Les nombres doivent être positifs et de 4 chiffres au plus
    >>> pretty_print2([7, 800, 32, 4500, 12345, -12])
    0007
    0800
    0032
    4500
    12345
    -012

    """
    for val in tab:
        print(f"{val:04d}")

def pretty_print3(tab: list[int]):
    """
    Écrit les nombres du tableau `tab` avec 4 chiffres
    (avec éventuellement des 0 devant)

    Les nombres doivent être positifs et de 4 chiffres au plus
    >>> pretty_print3([7, 800, 32, 4500, 12345, -12])
    0007
    0800
    0032
    4500
    2345
    0-12
    """
    for val in tab:
        sval = "000" + str(val)
        print(sval[-4:])

if __name__ == "__main__":
    import doctest
    doctest.testmod()

```

### Command used

```shell
pylint a.py
```

### Pylint output

<details open>
    <summary>
        pylint crashed with a ``AstroidError`` and with the following stacktrace:
    </summary>

```python
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pylint/lint/pylinter.py", line 788, in _lint_file
    check_astroid_module(module)
  File "/usr/lib/python3/dist-packages/pylint/lint/pylinter.py", line 1017, in check_astroid_module
    retval = self._check_astroid_module(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pylint/lint/pylinter.py", line 1069, in _check_astroid_module
    walker.walk(node)
  File "/usr/lib/python3/dist-packages/pylint/utils/ast_walker.py", line 94, in walk
    self.walk(child)
  File "/usr/lib/python3/dist-packages/pylint/utils/ast_walker.py", line 94, in walk
    self.walk(child)
  File "/usr/lib/python3/dist-packages/pylint/utils/ast_walker.py", line 94, in walk
    self.walk(child)
  File "/usr/lib/python3/dist-packages/pylint/utils/ast_walker.py", line 91, in walk
    callback(astroid)
  File "/usr/lib/python3/dist-packages/pylint/checkers/variables.py", line 1642, in visit_name
    self._loopvar_name(node)
  File "/usr/lib/python3/dist-packages/pylint/checkers/variables.py", line 2550, in _loopvar_name
    if astmts[i].statement().parent_of(stmt) and not utils.in_for_else_branch(
       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/astroid/nodes/node_ng.py", line 297, in statement
    return self.parent.statement()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/astroid/nodes/scoped_nodes/scoped_nodes.py", line 414, in statement
    raise StatementMissing(target=self)
astroid.exceptions.StatementMissing: Statement not found on <Module.corrections03 l.0 at 0x7ffff5581890>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pylint/lint/pylinter.py", line 752, in _lint_files
    self._lint_file(fileitem, module, check_astroid_module)
  File "/usr/lib/python3/dist-packages/pylint/lint/pylinter.py", line 790, in _lint_file
    raise astroid.AstroidError from e
astroid.exceptions.AstroidError

```

</details>

### Expected behavior

No crash.

### Pylint version

```shell
pylint 3.0.3
astroid 3.1.0
Python 3.11.9 (main, Apr 10 2024, 13:16:36) [GCC 13.2.0]
```

### OS / Environment

linux (Linux)

**Comment by jacobtylerwalls** [comment] 2024-04-17 15:07
Hi there, it seems you have an incompatible astroid version for pylint 3.0.3.

Duplicate of #9548

**Closed by jacobtylerwalls** 2024-04-17 15:07 UTC
