### ISSUE TITLE
Short circuit if all checks disabled

### ISSUE THREAD

**Issue by difhel** [pylint-dev/pylint#8715] opened 2023-05-25 21:29 UTC
### Bug description

Running "pylint test.py --disable=all" takes more than 3s!
```sh
$ touch test.py
$ time pylint test.py --disable=all

real    0m3.684s
user    0m0.000s
sys     0m0.015s
```
Running pylint without "disable=all" on a little project (150-lines telegram bot) takes more than 8s. It is non-usable.
```sh
$ time pylint main.py
************* Module main
main.py:137:7: R0133: Comparison between constants: '0 == 1' has a constant value (comparison-of-constants)
main.py:147:0: C0116: Missing function or method docstring (missing-function-docstring)

------------------------------------------------------------------
Your code has been rated at 9.57/10 (previous run: 9.57/10, +0.00)


real    0m8.352s
user    0m0.000s
sys     0m0.000s
```

### Command used

```shell
pylint test.py
```

### Pylint output

```shell
...
```

### Expected behavior

It is unacceptable that even on an empty file pylint runs for at least 3 seconds. I use the VS Code extension in my project, which for a small example with a 150-line project reacts to changes in 8 (!) seconds. This is literally impossible to use.

### Pylint version

```shell
$ pylint --version
pylint 2.17.4
astroid 2.15.5
Python 3.11.2 (tags/v3.11.2:878ead1, Feb  7 2023, 16:38:35) [MSC v.1934 64 bit (AMD64)]
```

### OS / Environment

Windows 11

**Comment by Pierre-Sassoulas** [comment] 2023-05-26 05:16
Hello, are you using any particular libraries or code construct ? As it is it's going to be impossible to reproduce.

**Comment by difhel** [comment] 2023-05-26 13:30
The gpt4free repository was cloned in this project, I added it to ignore in the .pylintrc file. This reduced the running time by only 2 seconds.
Checking the file with "\n":
```sh
$ echo "\n" > test.py && time pylint test.py
************* Module test
test.py:1:2: E0001: Parsing failed: 'unexpected character after line continuation character (<unknown>, line 1)' (syntax-error)

real    0m1.639s
user    0m0.000s
sys     0m0.015s
```
Checking the bot file (150 lines):
```sh
$time pylint main.py
************* Module main
main.py:137:7: R0133: Comparison between constants: '0 == 1' has a constant value (comparison-of-constants)
main.py:147:0: C0116: Missing function or method docstring (missing-function-docstring)

------------------------------------------------------------------
Your code has been rated at 9.57/10 (previous run: 9.57/10, +0.00)


real    0m6.689s
user    0m0.000s
sys     0m0.031s
```
There are no big files in the working directory.
I created an empty file in empty folder, here is the output of pylint:
```sh
$ mkdir pylint-testing && cd pylint-testing

$ touch test.py

$ time pylint test.py --disable=all

real    0m1.616s
user    0m0.000s
sys     0m0.015s

$ time pylint test.py

real    0m1.592s
user    0m0.000s
sys     0m0.000s
```
I don't think it's a problem of specific libraries. If you want me to share any logs or traces with you, let me know.

**Comment by mbyrnepr2** [comment] 2023-05-26 16:25
Duplicate of #5933 @Pierre-Sassoulas ?

**Comment by Pierre-Sassoulas** [comment] 2023-05-26 17:52
Or https://github.com/pylint-dev/astroid/issues/2161, but I don't think those perf issues are *that* bad so I suppose it's a pathological case on a specific lib / code construct and not a duplicate.

**Comment by jacobtylerwalls** [comment] 2023-05-27 17:50
Could you use a profiler like cProfile and post the result? You can profile:

from pylint.lint import Run
Run(["a.py", "disable=all"])

**Comment by jacobtylerwalls** [comment] 2023-06-26 13:25
> There are no big files in the working directory.

The size of the files is not material; it's what they import. If you import pandas, pylint is going to parse and replace the AST for pandas. That's going to take some time--it's part of pylint's distinct value proposition versus ruff, flake8, etc.

That said, I've seen a sprinkle of bug reports about `--disable=all` taking non-trivial time, so we may as well short circuit and just print the help message if a user disables everything.

**Comment by jacobtylerwalls** [comment] 2023-06-26 13:27
I rescoped it to "short circuit if all checks disabled" to make it actionable, but if you have a specific import statement you can share to advance the investigation, feel free to provide it. Otherwise it would be a duplicate of #5835 or #1416. Thanks.

**Closed** 2023-06-26 16:36 UTC
Labels: performance
