### ISSUE TITLE
Crash ``whilst running pylint in vscode``

### ISSUE THREAD

**Issue by gareth-walley** [pylint-dev/pylint#9801] opened 2024-07-16 11:37 UTC
When parsing the following ``base_test_case.py``:

As we are a private company, I am unable to share code. I tried to make a minimal viable example without giving any of our codebase away, but was unable to modify the code enough to make the error happen and not give anything away.

### Command used

```shell
/Users/<user_account>/Software/<project_name>/venv/bin/pylint --reports=n --output-format=json --ignore=<project_name>/core,<project_name>/web_service,tests/legacy_tests --disable=R --exit-zero --rcfile ../../.pylintrc --clear-cache-post-run=y --from-stdin /Users/<user_account>/Software/<project_name>/app/src/tests/test_presentation/test_presentation_flask_app/base_test_case.py
```

### Pylint output

<details open>
    <summary>
        pylint crashed with a ``AstroidError`` and with the following stacktrace:
    </summary>

```python
Traceback (most recent call last):
  File "/Users/<user_account>/Software/<project_name>/venv/lib/python3.11/site-packages/astroid/decorators.py", line 90, in inner
    yield next(generator)
          ^^^^^^^^^^^^^^^
  File "/Users/<user_account>/Software/<project_name>/venv/lib/python3.11/site-packages/astroid/decorators.py", line 44, in wrapped
    if context.push(node):
       ^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/<user_account>/Software/<project_name>/venv/lib/python3.11/site-packages/pylint/checkers/utils.py", line 1370, in safe_infer
    for inferred in infer_gen:
  File "/Users/<user_account>/Software/<project_name>/venv/lib/python3.11/site-packages/astroid/nodes/node_ng.py", line 169, in infer
    for i, result in enumerate(self._infer(context=context, **kwargs)):
  File "/Users/<user_account>/Software/<project_name>/venv/lib/python3.11/site-packages/astroid/decorators.py", line 103, in inner
    yield from generator
  File "/Users/<user_account>/Software/<project_name>/venv/lib/python3.11/site-packages/astroid/decorators.py", line 49, in wrapped
    for res in _func(node, context, **kwargs):
  File "/Users/<user_account>/Software/<project_name>/venv/lib/python3.11/site-packages/astroid/bases.py", line 179, in _infer_stmts
    for inf in stmt.infer(context=context):
  File "/Users/<user_account>/Software/<project_name>/venv/lib/python3.11/site-packages/astroid/nodes/node_ng.py", line 169, in infer
    for i, result in enumerate(self._infer(context=context, **kwargs)):
  File "/Users/<user_account>/Software/<project_name>/venv/lib/python3.11/site-packages/astroid/decorators.py", line 103, in inner
    yield from generator
  File "/Users/<user_account>/Software/<project_name>/venv/lib/python3.11/site-packages/astroid/decorators.py", line 49, in wrapped
    for res in _func(node, context, **kwargs):
  File "/Users/<user_account>/Software/<project_name>/venv/lib/python3.11/site-packages/astroid/bases.py", line 179, in _infer_stmts
    for inf in stmt.infer(context=context):
  File "/Users/<user_account>/Software/<project_name>/venv/lib/python3.11/site-packages/astroid/nodes/node_ng.py", line 169, in infer
    for i, result in enumerate(self._infer(context=context, **kwargs)):
  File "/Users/<user_account>/Software/<project_name>/venv/lib/python3.11/site-packages/astroid/decorators.py", line 103, in inner
    yield from generator
  File "/Users/<user_account>/Software/<project_name>/venv/lib/python3.11/site-packages/astroid/decorators.py", line 49, in wrapped
    for res in _func(node, context, **kwargs):
  File "/Users/<user_account>/Software/<project_name>/venv/lib/python3.11/site-packages/astroid/nodes/node_classes.py", line 3753, in _infer_subscript
    yield from assigned.infer(context)
  File "/Users/<user_account>/Software/<project_name>/venv/lib/python3.11/site-packages/astroid/nodes/node_ng.py", line 169, in infer
    for i, result in enumerate(self._infer(context=context, **kwargs)):
  File "/Users/<user_account>/Software/<project_name>/venv/lib/python3.11/site-packages/astroid/decorators.py", line 103, in inner
    yield from generator
  File "/Users/<user_account>/Software/<project_name>/venv/lib/python3.11/site-packages/astroid/decorators.py", line 49, in wrapped
    for res in _func(node, context, **kwargs):
  File "/Users/<user_account>/Software/<project_name>/venv/lib/python3.11/site-packages/astroid/nodes/node_classes.py", line 1765, in _infer
    yield from callee.infer_call_result(
  File "/Users/<user_account>/Software/<project_name>/venv/lib/python3.11/site-packages/astroid/bases.py", line 331, in infer_call_result
    for res in node.infer_call_result(caller, context):
  File "/Users/<user_account>/Software/<project_name>/venv/lib/python3.11/site-packages/astroid/bases.py", line 331, in infer_call_result
    for res in node.infer_call_result(caller, context):
  File "/Users/<user_account>/Software/<project_name>/venv/lib/python3.11/site-packages/astroid/bases.py", line 331, in infer_call_result
    for res in node.infer_call_result(caller, context):
  [Previous line repeated 947 more times]
  File "/Users/<user_account>/Software/<project_name>/venv/lib/python3.11/site-packages/astroid/bases.py", line 328, in infer_call_result
    for node in self._proxied.igetattr("__call__", context):
  File "/Users/<user_account>/Software/<project_name>/venv/lib/python3.11/site-packages/astroid/nodes/scoped_nodes/scoped_nodes.py", line 2511, in igetattr
    inferred._proxied.getattr("__get__", context)
  File "/Users/<user_account>/Software/<project_name>/venv/lib/python3.11/site-packages/astroid/nodes/scoped_nodes/scoped_nodes.py", line 2415, in getattr
    values += self._metaclass_lookup_attribute(name, context)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/<user_account>/Software/<project_name>/venv/lib/python3.11/site-packages/astroid/nodes/scoped_nodes/scoped_nodes.py", line 2439, in _metaclass_lookup_attribute
    attrs.update(set(cls_attributes))
                 ^^^^^^^^^^^^^^^^^^^
  File "/Users/<user_account>/Software/<project_name>/venv/lib/python3.11/site-packages/astroid/nodes/scoped_nodes/scoped_nodes.py", line 2446, in _get_attribute_from_metaclass
    attrs = cls.getattr(name, context=context, class_context=True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/<user_account>/Software/<project_name>/venv/lib/python3.11/site-packages/astroid/nodes/scoped_nodes/scoped_nodes.py", line 2415, in getattr
    values += self._metaclass_lookup_attribute(name, context)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/<user_account>/Software/<project_name>/venv/lib/python3.11/site-packages/astroid/nodes/scoped_nodes/scoped_nodes.py", line 2435, in _metaclass_lookup_attribute
    metaclass = self.metaclass(context=context)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/<user_account>/Software/<project_name>/venv/lib/python3.11/site-packages/astroid/nodes/scoped_nodes/scoped_nodes.py", line 2727, in metaclass
    return self._find_metaclass(context=context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/<user_account>/Software/<project_name>/venv/lib/python3.11/site-packages/astroid/nodes/scoped_nodes/scoped_nodes.py", line 2707, in _find_metaclass
    klass = self.declared_metaclass(context=context)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/<user_account>/Software/<project_name>/venv/lib/python3.11/site-packages/astroid/nodes/scoped_nodes/scoped_nodes.py", line 2679, in declared_metaclass
    for baseobj in base.infer(context=context):
  File "/Users/<user_account>/Software/<project_name>/venv/lib/python3.11/site-packages/astroid/nodes/node_ng.py", line 169, in infer
    for i, result in enumerate(self._infer(context=context, **kwargs)):
  File "/Users/<user_account>/Software/<project_name>/venv/lib/python3.11/site-packages/astroid/decorators.py", line 99, in inner
    raise InferenceError(
          ^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/<user_account>/Software/<project_name>/venv/lib/python3.11/site-packages/pylint/lint/pylinter.py", line 788, in _lint_file
    check_astroid_module(module)
  File "/Users/<user_account>/Software/<project_name>/venv/lib/python3.11/site-packages/pylint/lint/pylinter.py", line 1017, in check_astroid_module
    retval = self._check_astroid_module(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/<user_account>/Software/<project_name>/venv/lib/python3.11/site-packages/pylint/lint/pylinter.py", line 1069, in _check_astroid_module
    walker.walk(node)
  File "/Users/<user_account>/Software/<project_name>/venv/lib/python3.11/site-packages/pylint/utils/ast_walker.py", line 94, in walk
    self.walk(child)
  File "/Users/<user_account>/Software/<project_name>/venv/lib/python3.11/site-packages/pylint/utils/ast_walker.py", line 94, in walk
    self.walk(child)
  File "/Users/<user_account>/Software/<project_name>/venv/lib/python3.11/site-packages/pylint/utils/ast_walker.py", line 94, in walk
    self.walk(child)
  [Previous line repeated 1 more time]
  File "/Users/<user_account>/Software/<project_name>/venv/lib/python3.11/site-packages/pylint/utils/ast_walker.py", line 91, in walk
    callback(astroid)
  File "/Users/<user_account>/Software/<project_name>/venv/lib/python3.11/site-packages/pylint/checkers/classes/class_checker.py", line 1645, in visit_assignattr
    self._check_in_slots(node)
  File "/Users/<user_account>/Software/<project_name>/venv/lib/python3.11/site-packages/pylint/checkers/classes/class_checker.py", line 1680, in _check_in_slots
    inferred = safe_infer(node.expr)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/<user_account>/Software/<project_name>/venv/lib/python3.11/site-packages/pylint/checkers/utils.py", line 1392, in safe_infer
    raise AstroidError from e
astroid.exceptions.AstroidError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/<user_account>/Software/<project_name>/venv/lib/python3.11/site-packages/pylint/lint/pylinter.py", line 752, in _lint_files
    self._lint_file(fileitem, module, check_astroid_module)
  File "/Users/<user_account>/Software/<project_name>/venv/lib/python3.11/site-packages/pylint/lint/pylinter.py", line 790, in _lint_file
    raise astroid.AstroidError from e
astroid.exceptions.AstroidError

```

</details>

### Expected behavior

No crash.

### Pylint version

```shell
pylint 3.0.2
astroid 3.0.1
Python 3.11.6 (main, Nov  9 2023, 08:03:45) [Clang 14.0.0 (clang-1400.0.29.202)]
```

### OS / Environment

darwin (Darwin)

### Additional dependencies

```python
from pathlib import Path
import threading
from unittest import TestCase
from unittest.mock import Mock, create_autospec
import flask
from werkzeug.exceptions import InternalServerError
```

**Comment by jacobtylerwalls** [comment] 2024-07-16 11:47
Thanks for the report. Please reopen if you can reproduce on pylint 3.2.1 or higher.

Duplicate of #2432.

**Closed by jacobtylerwalls** 2024-07-16 11:47 UTC
