### ISSUE TITLE
pylint runs slow on sqlalchemy

### ISSUE THREAD

**Issue by jstucke** [pylint-dev/pylint#8673] opened 2023-05-10 16:25 UTC
### Bug description

Pylint somehow takes an unreasonable amount of time to lint some files. I especially noticed it with `sqlalchemy.func`.

### Command used

Minimal example:

```shell
docker run -it --rm --entrypoint=bash python:3.11
pip install sqlalchemy pylint
echo $'from sqlalchemy import func\n\nfunc.array_agg' > test.py
time pylint test.py
```

### Pylint output

```shell
************* Module test
/test.py:1:0: C0114: Missing module docstring (missing-module-docstring)
/test.py:3:0: W0104: Statement seems to have no effect (pointless-statement)

------------------------------------------------------------------
Your code has been rated at 0.00/10 (previous run: 0.00/10, +0.00)


real	0m29.884s
user	0m29.723s
sys	0m0.160s
```

### Expected behavior

I would not expect pylint to take almost 30 seconds for a two line file.

### Pylint version

```shell
pylint 2.17.4
astroid 2.15.4
python 3.11.2
```

### OS / Environment

Debian GNU/Linux 11 (bullseye)

**Comment by Pierre-Sassoulas** [comment] 2023-05-10 17:34
Thank you for opening the issue. I'm going to close as a duplicate of #8150, no one worked on it yet (sadly).

**Closed by Pierre-Sassoulas** 2023-05-10 17:34 UTC
Labels: Needs triage :inbox_tray:
