### ISSUE TITLE
Crash: AttributeError: 'TreeRebuilder' object has no attribute 'visit_typealias'

### ISSUE THREAD

**Issue by cofiem** [pylint-dev/pylint#8782] opened 2023-06-18 10:47 UTC
### Bug description

pylint crashed on mutiple files in [screenshot-ocr](https://github.com/cofiem/screenshot-ocr/blob/62e608370c95e164bf0665b88e7019c6db68497e/src/screenshot_ocr): app.py, google_sheets.py, ocr.py, trivia.py, utils.py

e.g.
```
src\screenshot_ocr\app.py:1:0: F0002: src\screenshot_ocr\app.py: Fatal error while checking 'src\screenshot_ocr\app.py'. Please open an issue in our bug tracker so we address this. There is a pre-filled template that you can use in '<userpath>\AppData\Local\pylint\pylint\Cache\pylint-crash-2023-06-18-20-35-13.txt'. (astroid-error)
```

pylint crashed with a ``AstroidError`` and with the following stacktrace:
```
Traceback (most recent call last):
  File "D:\Projects\Development\screenshot-ocr\.tox\py312\Lib\site-packages\pylint\checkers\imports.py", line 858, in _get_imported_module
    return importnode.do_import_module(modname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\Development\screenshot-ocr\.tox\py312\Lib\site-packages\astroid\nodes\_base_nodes.py", line 146, in do_import_module
    return mymodule.import_module(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\Development\screenshot-ocr\.tox\py312\Lib\site-packages\astroid\nodes\scoped_nodes\scoped_nodes.py", line 530, in import_module
    return AstroidManager().ast_from_module_name(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\Development\screenshot-ocr\.tox\py312\Lib\site-packages\astroid\manager.py", line 232, in ast_from_module_name
    return self.ast_from_file(found_spec.location, modname, fallback=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\Development\screenshot-ocr\.tox\py312\Lib\site-packages\astroid\manager.py", line 124, in ast_from_file
    return AstroidBuilder(self).file_build(filepath, modname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\Development\screenshot-ocr\.tox\py312\Lib\site-packages\astroid\builder.py", line 144, in file_build
    module, builder = self._data_build(data, modname, path)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\Development\screenshot-ocr\.tox\py312\Lib\site-packages\astroid\builder.py", line 204, in _data_build
    module = builder.visit_module(node, modname, node_file, package)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\Development\screenshot-ocr\.tox\py312\Lib\site-packages\astroid\rebuilder.py", line 254, in visit_module
    [self.visit(child, newnode) for child in node.body],
     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\Development\screenshot-ocr\.tox\py312\Lib\site-packages\astroid\rebuilder.py", line 609, in visit
    visit_method = getattr(self, visit_name)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TreeRebuilder' object has no attribute 'visit_typealias'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Projects\Development\screenshot-ocr\.tox\py312\Lib\site-packages\pylint\lint\pylinter.py", line 811, in _lint_file
    check_astroid_module(module)
  File "D:\Projects\Development\screenshot-ocr\.tox\py312\Lib\site-packages\pylint\lint\pylinter.py", line 1085, in check_astroid_module
    retval = self._check_astroid_module(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\Development\screenshot-ocr\.tox\py312\Lib\site-packages\pylint\lint\pylinter.py", line 1135, in _check_astroid_module
    walker.walk(node)
  File "D:\Projects\Development\screenshot-ocr\.tox\py312\Lib\site-packages\pylint\utils\ast_walker.py", line 94, in walk
    self.walk(child)
  File "D:\Projects\Development\screenshot-ocr\.tox\py312\Lib\site-packages\pylint\utils\ast_walker.py", line 91, in walk
    callback(astroid)
  File "D:\Projects\Development\screenshot-ocr\.tox\py312\Lib\site-packages\pylint\checkers\imports.py", line 549, in visit_importfrom
    imported_module = self._get_imported_module(node, basename)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\Development\screenshot-ocr\.tox\py312\Lib\site-packages\pylint\checkers\imports.py", line 883, in _get_imported_module
    raise astroid.AstroidError from e
astroid.exceptions.AstroidError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Projects\Development\screenshot-ocr\.tox\py312\Lib\site-packages\pylint\lint\pylinter.py", line 775, in _lint_files
    self._lint_file(fileitem, module, check_astroid_module)
  File "D:\Projects\Development\screenshot-ocr\.tox\py312\Lib\site-packages\pylint\lint\pylinter.py", line 813, in _lint_file
    raise astroid.AstroidError from e
astroid.exceptions.AstroidError
```

### Command used

```shell
python -X dev -m pylint src
```

### Pylint output

```shell
************* Module screenshot_ocr.app
src\screenshot_ocr\app.py:166:0: C0305: Trailing newlines (trailing-newlines)
src\screenshot_ocr\app.py:1:0: F0002: src\screenshot_ocr\app.py: Fatal error while checking 'src\screenshot_ocr\app.py'. Please open an issue in our bug tracker so we address this. There is a pre-filled template that you can use in '<userpath>\AppData\Local\pylint\pylint\Cache\pylint-crash-2023-06-18-20-35-13.txt'. (astroid-error)
```

### Expected behavior

Expected no crash.

### Pylint version

```shell
pylint 2.17.4
astroid 2.15.5
Python 3.12.0b1 (tags/v3.12.0b1:5612078, May 22 2023, 16:20:31) [MSC v.1934 64 bit (AMD64)]
```

### OS / Environment

Windows 10

**Comment by jacobtylerwalls** [comment] 2023-06-18 12:22
Python 3.12 isn't supported yet. Tracked in #7741

**Comment by jacobtylerwalls** [comment] 2023-06-18 12:23
Thanks for the report. (Duplicate of pylint-dev/astroid#2201.)

**Closed** 2023-06-18 12:24 UTC
Labels: Duplicate 🐫, Crash 💥

**Comment by jacobtylerwalls** [comment] 2023-08-08 16:51
Yes, the issue is fixed in the main branch. We're just waiting to issue a release until other issues are fixed also. You can install pylint from a github reference if you really need it before the release.
