### ISSUE TITLE
E1136: Value 'tuple' is unsubscriptable (unsubscriptable-object)

### ISSUE THREAD

**Issue by lazize** [pylint-dev/pylint#9243] opened 2023-11-17 12:57 UTC
### Bug description

```python
pylint doesn't recognize tuple as typing hint.

def my_func() -> tuple[str, str]:
  pass
```

### Command used

```shell
pylint --clear-cache-post-run yes --enable-all-extensions --py-version 3.9 --max-line-length 250 --max-args 10 --recursive yes .
```

### Pylint output

```python
$ pylint --clear-cache-post-run yes --enable-all-extensions --py-version 3.9 --max-line-length 250 --max-args 10 --recursive yes .
************* Module lambda
lambda.py:159:60: E1136: Value 'tuple' is unsubscriptable (unsubscriptable-object)
lambda.py:172:60: E1136: Value 'tuple' is unsubscriptable (unsubscriptable-object)
lambda.py:185:61: E1136: Value 'tuple' is unsubscriptable (unsubscriptable-object)
lambda.py:215:54: E1136: Value 'tuple' is unsubscriptable (unsubscriptable-object)
lambda.py:242:54: E1136: Value 'tuple' is unsubscriptable (unsubscriptable-object)
lambda.py:269:55: E1136: Value 'tuple' is unsubscriptable (unsubscriptable-object)
lambda.py:284:39: E1136: Value 'dict' is unsubscriptable (unsubscriptable-object)
lambda.py:284:98: E1136: Value 'list' is unsubscriptable (unsubscriptable-object)
lambda.py:301:20: E1136: Value 'dict' is unsubscriptable (unsubscriptable-object)
lambda.py:301:30: E1136: Value 'list' is unsubscriptable (unsubscriptable-object)
lambda.py:314:20: E1136: Value 'dict' is unsubscriptable (unsubscriptable-object)
lambda.py:314:30: E1136: Value 'list' is unsubscriptable (unsubscriptable-object)
lambda.py:327:20: E1136: Value 'dict' is unsubscriptable (unsubscriptable-object)
lambda.py:327:30: E1136: Value 'list' is unsubscriptable (unsubscriptable-object)
lambda.py:336:65: E1136: Value 'dict' is unsubscriptable (unsubscriptable-object)
lambda.py:336:75: E1136: Value 'list' is unsubscriptable (unsubscriptable-object)
lambda.py:345:18: E1136: Value 'list' is unsubscriptable (unsubscriptable-object)
lambda.py:451:12: E1136: Value 'dict' is unsubscriptable (unsubscriptable-object)
lambda.py:471:18: E1136: Value 'dict' is unsubscriptable (unsubscriptable-object)
lambda.py:551:20: E1136: Value 'dict' is unsubscriptable (unsubscriptable-object)

------------------------------------------------------------------
Your code has been rated at 5.99/10 (previous run: 5.61/10, +0.37)
```

### Expected behavior

No error message about tuple or dict typing hint.

### Pylint version

```shell
$ pylint --version
pylint 3.0.2
astroid 3.0.1
Python 3.8.10 (default, May 26 2023, 14:05:08)
[GCC 9.4.0]

Please note, event though the default python version is 3.8.10, I am running pylint with version 3.9.

$ python3.9 --version
Python 3.9.5
```

### OS / Environment

$ cat /etc/*release*
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.6 LTS"
NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.6 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

**Comment by jacobtylerwalls** [comment] 2023-11-17 13:01
Hi @lazize :wave:

Just to be sure I understand, when you say you're launching pylint with python 3.9, you don't mean the `py-version` option, right? How are you launching pylint with python 3.9 as `pylint` when `pylint --version` launches with 3.8? What happens if you launch pylint as `python3.9 -m pylint`?

**Comment by jacobtylerwalls** [comment] 2023-11-17 13:04
Duplicate of #8954

**Closed by jacobtylerwalls** 2023-11-17 13:04 UTC
Labels: Needs triage :inbox_tray:

**Comment by lazize** [comment] 2023-11-17 13:15
I meant `--py-version 3.9`.

But see below the output from the one you requested.

```shell
$ python3.9 -m pylint --version
pylint 2.17.4
astroid 2.15.6
Python 3.9.5 (default, Nov 23 2021, 15:27:38)
[GCC 9.3.0]
```

**Comment by jacobtylerwalls** [comment] 2023-11-17 13:28
Thanks for the question. You're right; the issue here is that py-version is not observed for this message, which is described in #8954.
