### ISSUE TITLE
Crash with astroid.exceptions.StatementMissing on redefined builtins

### ISSUE THREAD

**Issue by sattlerc** [pylint-dev/pylint#10159] opened 2024-12-29 06:38 UTC
### Bug description

When parsing the following ``a.py``:

```python
tuple = namedtuple(None, [])
```

### Command used

```shell
pylint a.py
```

### Pylint output

<details open>
    <summary>
        pylint crashed with a ``AstroidError`` and with the following stacktrace:
    </summary>

```
Traceback (most recent call last):
  File "/usr/lib/python3.13/site-packages/pylint/lint/pylinter.py", line 788, in _lint_file
    check_astroid_module(module)
    ~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/usr/lib/python3.13/site-packages/pylint/lint/pylinter.py", line 1017, in check_astroid_module
    retval = self._check_astroid_module(
        ast_node, walker, rawcheckers, tokencheckers
    )
  File "/usr/lib/python3.13/site-packages/pylint/lint/pylinter.py", line 1069, in _check_astroid_module
    walker.walk(node)
    ~~~~~~~~~~~^^^^^^
  File "/usr/lib/python3.13/site-packages/pylint/utils/ast_walker.py", line 90, in walk
    self.walk(child)
    ~~~~~~~~~^^^^^^^
  File "/usr/lib/python3.13/site-packages/pylint/utils/ast_walker.py", line 90, in walk
    self.walk(child)
    ~~~~~~~~~^^^^^^^
  File "/usr/lib/python3.13/site-packages/pylint/utils/ast_walker.py", line 87, in walk
    callback(astroid)
    ~~~~~~~~^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/pylint/checkers/base/name_checker/checker.py", line 423, in visit_assignname
    inferred_assign_type = utils.safe_infer(assign_type.value)
  File "/usr/lib/python3.13/site-packages/pylint/checkers/utils.py", line 1372, in safe_infer
    inferred_types.add(_get_python_type_of_node(value))
                       ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "/usr/lib/python3.13/site-packages/pylint/checkers/utils.py", line 1339, in _get_python_type_of_node
    return pytype()
  File "/usr/lib/python3.13/site-packages/astroid/nodes/scoped_nodes/scoped_nodes.py", line 2039, in pytype
    if self.newstyle:
       ^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/astroid/nodes/scoped_nodes/scoped_nodes.py", line 1995, in _newstyle_impl
    for base in self.ancestors(recurs=False, context=context):
                ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/astroid/nodes/scoped_nodes/scoped_nodes.py", line 2245, in ancestors
    for baseobj in stmt.infer(context):
                   ~~~~~~~~~~^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/astroid/nodes/node_ng.py", line 168, in infer
    for i, result in enumerate(self._infer(context=context, **kwargs)):
                     ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/astroid/decorators.py", line 86, in inner
    yield next(generator)
          ~~~~^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/astroid/decorators.py", line 49, in wrapped
    for res in _func(node, context, **kwargs):
               ~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/astroid/nodes/node_classes.py", line 585, in _infer
    frame, stmts = self.lookup(self.name)
                   ~~~~~~~~~~~^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/astroid/nodes/_base_nodes.py", line 277, in lookup
    return self.scope().scope_lookup(self, name)
           ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/astroid/nodes/scoped_nodes/scoped_nodes.py", line 328, in scope_lookup
    return self._scope_lookup(node, name, offset)
           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/astroid/nodes/scoped_nodes/mixin.py", line 80, in _scope_lookup
    stmts = _filter_stmts(node, self.locals[name], self, offset)
  File "/usr/lib/python3.13/site-packages/astroid/filter_statements.py", line 90, in _filter_stmts
    if base_node.parent and base_node.statement() is myframe and myframe.parent:
                            ~~~~~~~~~~~~~~~~~~~^^
  File "/usr/lib/python3.13/site-packages/astroid/nodes/node_ng.py", line 295, in statement
    return self.parent.statement()
           ~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/lib/python3.13/site-packages/astroid/nodes/scoped_nodes/scoped_nodes.py", line 413, in statement
    raise StatementMissing(target=self)
astroid.exceptions.StatementMissing: Statement not found on <Module.a l.0 at 0x7ee17d2a3950>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.13/site-packages/pylint/lint/pylinter.py", line 752, in _lint_files
    self._lint_file(fileitem, module, check_astroid_module)
    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/pylint/lint/pylinter.py", line 790, in _lint_file
    raise astroid.AstroidError from e
astroid.exceptions.AstroidError
```

### Expected behavior

No crash.

### Pylint version

```shell
pylint 3.3.3
astroid 3.3.8
Python 3.13.1 (main, Dec  4 2024, 18:05:56) [GCC 14.2.1 20240910]
```

**Comment by sattlerc** [comment] 2024-12-29 06:43
Possibly related: #8079, #8210

**Comment by jacobtylerwalls** [comment] 2024-12-29 07:30
Thanks for the report and finding the other issues 👌🏻

Agree this is a duplicate of #8079

**Closed** 2024-12-29 07:30 UTC
Labels: Duplicate 🐫
