### ISSUE TITLE
Crash (astroid Error) – "Catching too general exception Exception"

### ISSUE THREAD

**Issue by ferricoxide** [pylint-dev/pylint#8771] opened 2023-06-13 11:37 UTC
### Bug description

Submitting bug per `pylint` error-output.

When parsing the following file/contents, pylint crashes:

```python
# -*- coding: utf-8 -*-
"""
Provide custom modules for ash-linux.

:maintainer: Loren Gordon <loren.gordon@plus3it.com>
"""
import os
import re

try:
    from salt.utils.files import fopen
except ImportError:
    from salt.utils import fopen

__virtualname__ = "ash"


def __virtual__():
    if __grains__.get("kernel", "") == "Linux":
        return __virtualname__
    return False, "ash_linux module works only on Linux systems"


def _move_boot_kernel(restore_bak):
    """
    Create/restore backup of boot-kernel file.

    Args:
        restore_bak:  (`obj`: `bool`)
        True if restoring backup of boot-kernel. False to create a backup.
    """
    if restore_bak:
        filename = "initramfs-" + os.uname()[2] + ".img.bak"
        new_path = os.path.join("/boot", filename[:-4])
    else:
        filename = "initramfs-" + os.uname()[2] + ".img"
        new_path = os.path.join("/boot", filename + ".bak")

    old_path = os.path.join("/boot", filename)
    if os.path.exists(old_path):
        __salt__["file.move"](old_path, new_path)

    return old_path


def _get_default_kernel():
    """Obtain default kernel from grubby command."""
    cmd = "grubby --default-kernel"
    return __salt__["cmd.run"](cmd, python_shell=True, output_loglevel="quiet")


def _get_boot_path():
    """Obtain path that kernel is located in."""
    boot_path = _get_default_kernel()
    return boot_path[: boot_path.rindex("/")] or "/"


def _get_boot_mount(boot_path):
    """Obtain mount to path that kernel is located in."""
    cmd = "findmnt -no source -T " + boot_path
    return __salt__["cmd.run"](cmd, python_shell=True, output_loglevel="quiet")


def _modify_grub_file(rmv_fips_arg):
    """
    Insert/remove fips argument from GRUB file in /etc/default.

    Args:
        rmv_fips_arg:  (`obj`: `bool`)
        True if removing fips argument. False to add it.
    """
    filepath = "/etc/default/grub"
    if rmv_fips_arg:
        result = __salt__["file.replace"](filepath, "fips=1[ ]", "")
    else:
        grub_marker = 'GRUB_CMDLINE_LINUX="'
        grub_args = []
        check = __salt__["file.search"](filepath, "boot=")
        if not check:
            # No boot= in grub, so find mount where kernel is located.
            # Add boot= argument if a boot path exists.
            boot_mount = _get_boot_mount(_get_boot_path())
            if boot_mount != _get_boot_mount("/"):
                grub_args.append("boot={0} ".format(boot_mount))

        check = __salt__["file.search"](filepath, "fips=1")
        if not check:
            grub_args.append("fips=1 ")

        if grub_args:
            result = __salt__["file.replace"](
                filepath, grub_marker, "{0}{1}".format(grub_marker, "".join(grub_args))
            )
        else:
            result = None

    return result


def _is_fips_in_kernel():
    """Checks image file for fips module."""
    filename = "initramfs-" + os.uname()[2] + ".img"
    filepath = os.path.join("/boot", filename)
    cmd = "lsinitrd -m {0} | grep fips".format(filepath)
    result = (
        __salt__["cmd.run"](cmd, python_shell=True, output_loglevel="quiet") == "fips"
    )
    return result


def _get_installed_dracutfips_pkgs():
    """
    Returns list of available dracut-fips pkgs to install. We currently
    resort to using an actual call to yum as Salt's pkg.list_repo_pkgs()
    does not look in repos that have been enabled like "enabled = 1"
    instead of "enabled=1".  Once that has been addressed in Salt, we can
    update this to use Salt's command.
    """
    cmd = "yum list installed"
    available_pkgs = __salt__["cmd.run"](cmd, python_shell=False)
    return re.findall(r"\bdracut-fips[^.]*", available_pkgs)


def _get_grub_args():
    """Obtain arguments line in grubby command."""
    cmd = "grubby --info=" + _get_default_kernel() + " | grep args="
    return __salt__["cmd.run"](cmd, python_shell=True, output_loglevel="quiet")


def _rollback_fips_disable(installed_fips_pkgs):
    """
    Rollback the actions of fips_disable() upon a thrown error.

    Args:
        installed_fips_pkgs:  (`obj`: `list`)
        List of installed dracut-fips packages that were removed
        during the process of running fips_disable().
    """
    __salt__["pkg.install"](installed_fips_pkgs)

    if not _is_fips_in_kernel():
        _move_boot_kernel(True)

    grub_bak = "/etc/default/grub.bak"
    if os.path.exists(grub_bak):
        __salt__["file.move"](grub_bak, "/etc/default/grub")

    __salt__["cmd.run"]("grubby --update-kernel=ALL --args=fips=1", python_shell=False)


def fips_disable():
    """
    Disables FIPS on RH/CentOS system. Note that you must reboot the
    system in order for FIPS to be disabled.  This routine prepares
    the system to disable FIPS.

    CLI Example:
    .. code-block:: bash
        salt '*' ash.fips_disable
    """
    installed_fips_pkgs = _get_installed_dracutfips_pkgs()
    ret = {"result": True}
    old = {}
    new = {}

    try:
        # Remove dracut-fips installations.
        installed_fips_pkgs = _get_installed_dracutfips_pkgs()
        if "dracut-fips" in installed_fips_pkgs:
            __salt__["pkg.remove"]("dracut-fips")
            old["Packages"] = installed_fips_pkgs

        # If fips is in kernel, create a new boot-kernel.
        if _is_fips_in_kernel():
            _move_boot_kernel(False)
            __salt__["cmd.run"]("dracut -f", python_shell=False)

        # Update grub.cfg file to remove the fips argument.
        grub_args = _get_grub_args()
        if "fips=1" in grub_args:
            cmd = "grubby --update-kernel=ALL --remove-args=fips=1"
            __salt__["cmd.run"](cmd, python_shell=False)
            new["grubby"] = cmd

        # Update GRUB command line entry to remove fips.
        diff = _modify_grub_file(True)
        if diff:
            new["/etc/default/grub"] = diff
    except Exception:
        _rollback_fips_disable(installed_fips_pkgs)
        ret["result"] = False
        ret["changes"] = {}
        ret["comment"] = "Unable to change state of system to FIPS-disabled."
    else:
        if old:
            ret["changes"] = {"old": old}
            ret["comment"] = "FIPS has been toggled to off."
        if new:
            if "changes" in ret:
                ret["changes"].update({"new": new})
            else:
                ret["changes"] = {"new": new}
            ret["comment"] = "FIPS has been toggled to off."
        if fips_status() == "enabled":
            msg = " Reboot system to place into FIPS-disabled state."
            if "comment" in ret:
                ret["comment"] = ret["comment"] + msg
            else:
                ret["comment"] = msg[1:]
        if "changes" not in ret and "comment" not in ret:
            ret["comment"] = "FIPS mode is already disabled. No changes."
    finally:
        return ret


def _rollback_fips_enable():
    """Rollback the actions of fips_enable() upon a thrown error."""
    __salt__["pkg.remove"]("dracut-fips")

    if _is_fips_in_kernel():
        _move_boot_kernel(True)

    grub_bak = "/etc/default/grub.bak"
    if os.path.exists(grub_bak):
        __salt__["file.move"](grub_bak, "/etc/default/grub")

    __salt__["cmd.run"](
        "grubby --update-kernel=ALL --remove-args=fips=1", python_shell=False
    )


def fips_enable():
    """
    Enables FIPS on RH/CentOS system.  Note that you must reboot the
    system in order for FIPS to be disabled.  This routine prepares
    the system to disable FIPS.

    CLI Example:
    .. code-block:: bash
        salt '*' ash.fips_enable
    """
    ret = {"result": True}
    new = {}

    try:
        # Install dracut-fips package.
        installed_fips_pkgs = _get_installed_dracutfips_pkgs()
        if "dracut-fips" not in installed_fips_pkgs:
            __salt__["pkg.install"]("dracut-fips")
            installed_fips_pkgs = _get_installed_dracutfips_pkgs()
            new["Packages"] = installed_fips_pkgs

        # If fips is not in kernel, create a new boot-kernel.
        if not _is_fips_in_kernel():
            _move_boot_kernel(False)
            __salt__["cmd.run"]("dracut -f", python_shell=False)

        # Update grub.cfg file to add the fips and boot agurments.
        grubby_args = []
        grub_args = _get_grub_args()
        if "fips=1" not in grub_args:
            grubby_args.append("fips=1")

        # Add boot= argument if a boot path exists.
        boot_mount = _get_boot_mount(_get_boot_path())
        if "boot=" not in grub_args and boot_mount != _get_boot_mount("/"):
            grubby_args.append("boot={0}".format(boot_mount))
        if grubby_args:
            cmd = 'grubby --update-kernel=ALL --args="{0}"'.format(
                " ".join(grubby_args)
            )
            __salt__["cmd.run"](cmd, python_shell=False)
            new["grubby"] = cmd

        # Update GRUB command line entry to add fips.
        diff = _modify_grub_file(False)
        if diff:
            new["/etc/default/grub"] = diff
    except Exception:
        _rollback_fips_enable()
        ret["result"] = False
        ret["comment"] = "Unable to change state of system to FIPS-enabled."
    else:
        if new:
            ret["changes"] = {"new": new}
            ret["comment"] = "FIPS has been toggled to on."
        if fips_status() == "disabled":
            msg = " Reboot system to place into FIPS-enabled state."
            if "comment" in ret:
                ret["comment"] = ret["comment"] + msg
            else:
                ret["comment"] = msg[1:]
        if "changes" not in ret and "comment" not in ret:
            ret["comment"] = "FIPS mode is already enabled. No changes."
    finally:
        return ret


def fips_status():
    """
    Returns the status of fips on the currently running system.

    Returns a `str` of "enabled" if FIPS is enabled. Otherwise,
    returns a `str` of "disabled".

    CLI Example:
    .. code-block:: bash
        salt '*' ash.fips_status
    """
    try:
        with fopen("/proc/sys/crypto/fips_enabled", "r") as fle:
            return "enabled" if fle.read().strip() == "1" else "disabled"
    except (IOError, FileNotFoundError):
        return "disabled"

```

### Configuration

Configuration is presumably not relevant. However, `pylinit` configuration is accessible as [part of branch](https://github.com/ferricoxide/ash-linux-formula/blob/Issue_409/.pylintrc) pending merge (pylint is used via github actions)

<details>

<summary>EDIT: here is the rcfile</summary>

```
[MASTER]

# A comma-separated list of package or module names from where C extensions may
# be loaded. Extensions are loading into the active Python interpreter and may
# run arbitrary code.
extension-pkg-whitelist=

# Specify a score threshold to be exceeded before program exits with error.
fail-under=10.0

# Add files or directories to the blacklist. They should be base names, not
# paths.
ignore=CVS

# Add files or directories matching the regex patterns to the blacklist. The
# regex matches against base names, not paths.
ignore-patterns=

# Python code to execute, usually for sys.path manipulation such as
# pygtk.require().
#init-hook=

# Use multiple processes to speed up Pylint. Specifying 0 will auto-detect the
# number of processors available to use.
jobs=1

# Control the amount of potential inferred values when inferring a single
# object. This can help the performance when dealing with large functions or
# complex, nested conditions.
limit-inference-results=100

# List of plugins (as comma separated values of python module names) to load,
# usually to register additional checkers.
load-plugins=pylint_pytest

# Pickle collected data for later comparisons.
persistent=yes

# When enabled, pylint would attempt to guess common misconfiguration and emit
# user-friendly hints instead of false-positive error messages.
suggestion-mode=yes

# Allow loading of arbitrary C extensions. Extensions are imported into the
# active Python interpreter and may run arbitrary code.
unsafe-load-any-extension=no


[MESSAGES CONTROL]

# Only show warnings with the listed confidence levels. Leave empty to show
# all. Valid levels: HIGH, INFERENCE, INFERENCE_FAILURE, UNDEFINED.
confidence=

# Disable the message, report, category or checker with the given id(s). You
# can either give multiple identifiers separated by comma (,) or put this
# option multiple times (only on the command line, not in the configuration
# file where it should appear only once). You can also use "--disable=all" to
# disable everything first and then reenable specific checks. For example, if
# you want to run only the similarities checker, you can use "--disable=all
# --enable=similarities". If you want to run only the classes checker, but have
# no Warning level messages displayed, use "--disable=all --enable=classes
# --disable=W".
disable=raw-checker-failed,
        bad-inline-option,
        locally-disabled,
        file-ignored,
        suppressed-message,
        useless-suppression,
        deprecated-pragma,
        use-symbolic-message-instead,
        consider-using-f-string,

# Enable the message, report, category or checker with the given id(s). You can
# either give multiple identifier separated by comma (,) or put this option
# multiple time (only on the command line, not in the configuration file where
# it should appear only once). See also the "--disable" option for examples.
enable=c-extension-no-member


[REPORTS]

# Python expression which should return a score less than or equal to 10. You
# have access to the variables 'error', 'warning', 'refactor', and 'convention'
# which contain the number of messages in each category, as well as 'statement'
# which is the total number of statements analyzed. This score is used by the
# global evaluation report (RP0004).
evaluation=10.0 - ((float(5 * error + warning + refactor + convention) / statement) * 10)

# Template used to display messages. This is a python new-style format string
# used to format the message information. See doc for all details.
#msg-template=

# Set the output format. Available formats are text, parseable, colorized, json
# and msvs (visual studio). You can also give a reporter class, e.g.
# mypackage.mymodule.MyReporterClass.
output-format=text

# Tells whether to display a full report or only the messages.
reports=no

# Activate the evaluation score.
score=yes


[REFACTORING]

# Maximum number of nested blocks for function / method body
max-nested-blocks=5

# Complete name of functions that never returns. When checking for
# inconsistent-return-statements if a never returning function is called then
# it will be considered as an explicit return statement and no message will be
# printed.
never-returning-functions=sys.exit


[BASIC]

# Naming style matching correct argument names.
argument-naming-style=snake_case

# Regular expression matching correct argument names. Overrides argument-
# naming-style.
#argument-rgx=

# Naming style matching correct attribute names.
attr-naming-style=snake_case

# Regular expression matching correct attribute names. Overrides attr-naming-
# style.
#attr-rgx=

# Bad variable names which should always be refused, separated by a comma.
bad-names=foo,
          bar,
          baz,
          toto,
          tutu,
          tata

# Bad variable names regexes, separated by a comma. If names match any regex,
# they will always be refused
bad-names-rgxs=

# Naming style matching correct class attribute names.
class-attribute-naming-style=any

# Regular expression matching correct class attribute names. Overrides class-
# attribute-naming-style.
#class-attribute-rgx=

# Naming style matching correct class names.
class-naming-style=PascalCase

# Regular expression matching correct class names. Overrides class-naming-
# style.
#class-rgx=

# Naming style matching correct constant names.
const-naming-style=UPPER_CASE

# Regular expression matching correct constant names. Overrides const-naming-
# style.
#const-rgx=

# Minimum line length for functions/classes that require docstrings, shorter
# ones are exempt.
docstring-min-length=-1

# Naming style matching correct function names.
function-naming-style=snake_case

# Regular expression matching correct function names. Overrides function-
# naming-style.
#function-rgx=

# Good variable names which should always be accepted, separated by a comma.
good-names=i,
           j,
           k,
           ex,
           Run,
           _

# Good variable names regexes, separated by a comma. If names match any regex,
# they will always be accepted
good-names-rgxs=

# Include a hint for the correct naming format with invalid-name.
include-naming-hint=no

# Naming style matching correct inline iteration names.
inlinevar-naming-style=any

# Regular expression matching correct inline iteration names. Overrides
# inlinevar-naming-style.
#inlinevar-rgx=

# Naming style matching correct method names.
method-naming-style=snake_case

# Regular expression matching correct method names. Overrides method-naming-
# style.
#method-rgx=

# Naming style matching correct module names.
module-naming-style=snake_case

# Regular expression matching correct module names. Overrides module-naming-
# style.
#module-rgx=

# Colon-delimited sets of names that determine each other's naming style when
# the name regexes allow several styles.
name-group=

# Regular expression which should only match function or class names that do
# not require a docstring.
no-docstring-rgx=^_

# List of decorators that produce properties, such as abc.abstractproperty. Add
# to this list to register other decorators that produce valid properties.
# These decorators are taken in consideration only for invalid-name.
property-classes=abc.abstractproperty

# Naming style matching correct variable names.
variable-naming-style=snake_case

# Regular expression matching correct variable names. Overrides variable-
# naming-style.
#variable-rgx=


[FORMAT]

# Expected format of line ending, e.g. empty (any line ending), LF or CRLF.
expected-line-ending-format=

# Regexp for a line that is allowed to be longer than the limit.
ignore-long-lines=^\s*(# )?<?https?://\S+>?$

# Number of spaces of indent required inside a hanging or continued line.
indent-after-paren=4

# String used as indentation unit. This is usually "    " (4 spaces) or "\t" (1
# tab).
indent-string='    '

# Maximum number of characters on a single line.
max-line-length=88

# Maximum number of lines in a module.
max-module-lines=1000

# Allow the body of a class to be on the same line as the declaration if body
# contains single statement.
single-line-class-stmt=no

# Allow the body of an if to be on the same line as the test if there is no
# else.
single-line-if-stmt=no


[LOGGING]

# The type of string formatting that logging methods do. `old` means using %
# formatting, `new` is for `{}` formatting.
logging-format-style=old

# Logging modules to check that the string format arguments are in logging
# function parameter format.
logging-modules=logging


[MISCELLANEOUS]

# List of note tags to take in consideration, separated by a comma.
notes=FIXME,
      XXX,
      TODO

# Regular expression of note tags to take in consideration.
#notes-rgx=


[SIMILARITIES]

# Ignore comments when computing similarities.
ignore-comments=yes

# Ignore docstrings when computing similarities.
ignore-docstrings=yes

# Ignore imports when computing similarities.
ignore-imports=no

# Minimum lines number of a similarity.
min-similarity-lines=4


[SPELLING]

# Limits count of emitted suggestions for spelling mistakes.
max-spelling-suggestions=4

# Spelling dictionary name. Available dictionaries: none. To make it work,
# install the python-enchant package.
spelling-dict=

# List of comma separated words that should not be checked.
spelling-ignore-words=

# A path to a file that contains the private dictionary; one word per line.
spelling-private-dict-file=

# Tells whether to store unknown words to the private dictionary (see the
# --spelling-private-dict-file option) instead of raising a message.
spelling-store-unknown-words=no


[STRING]

# This flag controls whether inconsistent-quotes generates a warning when the
# character used as a quote delimiter is used inconsistently within a module.
check-quote-consistency=no

# This flag controls whether the implicit-str-concat should generate a warning
# on implicit string concatenation in sequences defined over several lines.
check-str-concat-over-line-jumps=no


[TYPECHECK]

# List of decorators that produce context managers, such as
# contextlib.contextmanager. Add to this list to register other decorators that
# produce valid context managers.
contextmanager-decorators=contextlib.contextmanager

# List of members which are set dynamically and missed by pylint inference
# system, and so shouldn't trigger E1101 when accessed. Python regular
# expressions are accepted.
generated-members=

# Tells whether missing members accessed in mixin class should be ignored. A
# mixin class is detected if its name ends with "mixin" (case insensitive).
ignore-mixin-members=yes

# Tells whether to warn about missing members when the owner of the attribute
# is inferred to be None.
ignore-none=yes

# This flag controls whether pylint should warn about no-member and similar
# checks whenever an opaque object is returned when inferring. The inference
# can return multiple potential results while evaluating a Python object, but
# some branches might not be evaluated, which results in partial inference. In
# that case, it might be useful to still emit no-member and other checks for
# the rest of the inferred objects.
ignore-on-opaque-inference=yes

# List of class names for which member attributes should not be checked (useful
# for classes with dynamically set attributes). This supports the use of
# qualified names.
ignored-classes=optparse.Values,thread._local,_thread._local

# List of module names for which member attributes should not be checked
# (useful for modules/projects where namespaces are manipulated during runtime
# and thus existing member attributes cannot be deduced by static analysis). It
# supports qualified module names, as well as Unix pattern matching.
ignored-modules=

# Show a hint with possible names when a member name was not found. The aspect
# of finding the hint is based on edit distance.
missing-member-hint=yes

# The minimum edit distance a name should have in order to be considered a
# similar match for a missing member name.
missing-member-hint-distance=1

# The total number of similar names that should be taken in consideration when
# showing a hint for a missing member.
missing-member-max-choices=1

# List of decorators that change the signature of a decorated function.
signature-mutators=


[VARIABLES]

# List of additional names supposed to be defined in builtins. Remember that
# you should avoid defining new builtins when possible.
additional-builtins=__salt__,
                    __grains__,

# Tells whether unused global variables should be treated as a violation.
allow-global-unused-variables=yes

# List of strings which can identify a callback function by name. A callback
# name must start or end with one of those strings.
callbacks=cb_,
          _cb

# A regular expression matching the name of dummy variables (i.e. expected to
# not be used).
dummy-variables-rgx=_+$|(_[a-zA-Z0-9_]*[a-zA-Z0-9]+?$)|dummy|^ignored_|^unused_

# Argument names that match this expression will be ignored. Default to name
# with leading underscore.
ignored-argument-names=_.*|^ignored_|^unused_

# Tells whether we should check for unused import in __init__ files.
init-import=no

# List of qualified module names which can have objects that can redefine
# builtins.
redefining-builtins-modules=six.moves,past.builtins,future.builtins,builtins,io


[CLASSES]

# List of method names used to declare (i.e. assign) instance attributes.
defining-attr-methods=__init__,
                      __new__,
                      setUp,
                      __post_init__

# List of member names, which should be excluded from the protected access
# warning.
exclude-protected=_asdict,
                  _fields,
                  _replace,
                  _source,
                  _make

# List of valid names for the first argument in a class method.
valid-classmethod-first-arg=cls

# List of valid names for the first argument in a metaclass class method.
valid-metaclass-classmethod-first-arg=cls


[DESIGN]

# Maximum number of arguments for function / method.
max-args=5

# Maximum number of attributes for a class (see R0902).
max-attributes=7

# Maximum number of boolean expressions in an if statement (see R0916).
max-bool-expr=5

# Maximum number of branch for function / method body.
max-branches=12

# Maximum number of locals for function / method body.
max-locals=15

# Maximum number of parents for a class (see R0901).
max-parents=7

# Maximum number of public methods for a class (see R0904).
max-public-methods=20

# Maximum number of return / yield for function / method body.
max-returns=6

# Maximum number of statements in function / method body.
max-statements=50

# Minimum number of public methods for a class (see R0903).
min-public-methods=2


[IMPORTS]

# List of modules that can be imported at any level, not just the top level
# one.
allow-any-import-level=

# Allow wildcard imports from modules that define __all__.
allow-wildcard-with-all=no

# Analyse import fallback blocks. This can be used to support both Python 2 and
# 3 compatible code, which means that the block might have code that exists
# only in one or another interpreter, leading to false positives when analysed.
analyse-fallback-blocks=no

# Deprecated modules which should not be used, separated by a comma.
deprecated-modules=optparse,tkinter.tix

# Create a graph of external dependencies in the given file (report RP0402 must
# not be disabled).
ext-import-graph=

# Create a graph of every (i.e. internal and external) dependencies in the
# given file (report RP0402 must not be disabled).
import-graph=

# Create a graph of internal dependencies in the given file (report RP0402 must
# not be disabled).
int-import-graph=

# Force import order to recognize a module as part of the standard
# compatibility libraries.
known-standard-library=

# Force import order to recognize a module as part of a third party library.
known-third-party=enchant

# Couples of modules and preferred modules, separated by a comma.
preferred-modules=


[EXCEPTIONS]

# Exceptions that will emit a warning when being caught. Defaults to
# "BaseException, Exception".
overgeneral-exceptions=builtins.BaseException,
                       builtins.Exception
```
</details>

### Command used

```shell
Executed via GitHub action:


for python_file in _modules/ash_linux.py _states/ash_linux.py; do \
	echo "[python/lint/exec]: pylint file: $python_file"; \
	python3 -m pylint --rcfile /workdir/.pylintrc \
		--msg-template="{path}:{line} [{symbol}] {msg}" \
		--report no --score no $python_file; \
done
```

### Pylint output

```shell
pylint crashed with a ``AstroidError`` and with the following stacktrace:

Traceback (most recent call last):
  File "/home/tardigrade-ci/.local/lib/python3.12/site-packages/astroid/inference.py", line 450, in infer_subscript
    assigned = value.getitem(index_value, context)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tardigrade-ci/.local/lib/python3.12/site-packages/astroid/nodes/node_classes.py", line 2466, in getitem
    raise AstroidIndexError(index)
astroid.exceptions.AstroidIndexError: <exception str() failed>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/tardigrade-ci/.local/lib/python3.12/site-packages/pylint/lint/pylinter.py", line 798, in _lint_file
    check_astroid_module(module)
  File "/home/tardigrade-ci/.local/lib/python3.12/site-packages/pylint/lint/pylinter.py", line 1067, in check_astroid_module
    retval = self._check_astroid_module(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tardigrade-ci/.local/lib/python3.12/site-packages/pylint/lint/pylinter.py", line 1117, in _check_astroid_module
    walker.walk(node)
  File "/home/tardigrade-ci/.local/lib/python3.12/site-packages/pylint/utils/ast_walker.py", line 94, in walk
    self.walk(child)
  File "/home/tardigrade-ci/.local/lib/python3.12/site-packages/pylint/utils/ast_walker.py", line 94, in walk
    self.walk(child)
  File "/home/tardigrade-ci/.local/lib/python3.12/site-packages/pylint/utils/ast_walker.py", line 94, in walk
    self.walk(child)
  [Previous line repeated 4 more times]
  File "/home/tardigrade-ci/.local/lib/python3.12/site-packages/pylint/utils/ast_walker.py", line 91, in walk
    callback(astroid)
  File "/home/tardigrade-ci/.local/lib/python3.12/site-packages/pylint/checkers/base/basic_checker.py", line 705, in visit_call
    if utils.is_terminating_func(node):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tardigrade-ci/.local/lib/python3.12/site-packages/pylint/checkers/utils.py", line 2181, in is_terminating_func
    return True
           ^^^^
  File "/home/tardigrade-ci/.local/lib/python3.12/site-packages/astroid/nodes/node_ng.py", line 171, in infer
    yield from self._infer(context=context, **kwargs)
  File "/home/tardigrade-ci/.local/lib/python3.12/site-packages/astroid/decorators.py", line 142, in raise_if_nothing_inferred
    yield next(generator)
          ^^^^^^^^^^^^^^^
  File "/home/tardigrade-ci/.local/lib/python3.12/site-packages/astroid/decorators.py", line 119, in wrapped
    yielded.add(ares)
  File "/home/tardigrade-ci/.local/lib/python3.12/site-packages/astroid/inference.py", line 380, in infer_attribute
    context.boundnode = old_boundnode
    ^^^^^^^^^^^^^^^^^
  File "/home/tardigrade-ci/.local/lib/python3.12/site-packages/astroid/nodes/node_ng.py", line 184, in infer
    for i, result in enumerate(self._infer(context=context, **kwargs)):
  File "/home/tardigrade-ci/.local/lib/python3.12/site-packages/astroid/decorators.py", line 142, in raise_if_nothing_inferred
    yield next(generator)
          ^^^^^^^^^^^^^^^
  File "/home/tardigrade-ci/.local/lib/python3.12/site-packages/astroid/decorators.py", line 119, in wrapped
    yielded.add(ares)
  File "/home/tardigrade-ci/.local/lib/python3.12/site-packages/astroid/inference.py", line 458, in infer_subscript
    raise InferenceError(node=self, context=context) from exc
astroid.exceptions.InferenceError: Inference failed for <Subscript l.200 at 0x7f91d98ebe90>.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/tardigrade-ci/.local/lib/python3.12/site-packages/pylint/lint/pylinter.py", line 763, in _lint_files
    self._lint_file(fileitem, module, check_astroid_module)
  File "/home/tardigrade-ci/.local/lib/python3.12/site-packages/pylint/lint/pylinter.py", line 800, in _lint_file
    raise astroid.AstroidError from e
astroid.exceptions.AstroidError
```
```


### Expected behavior

Pylint either exits clean or with identifiable lint-fix suggestion

### Pylint version

```shell
$ pylint --version
pylint 2.16.2
astroid 2.14.2
Python 3.12.0a5 (main, Feb 11 2023, 02:14:53) [GCC 8.3.0]
```
```


### OS / Environment

Container launched by GitHub Actions executor. Container-creation statement is:

```bash
DOCKER_BUILDKIT=1 docker build -t ash-linux-formula:latest \
	--build-arg PROJECT_NAME=tardigrade-ci \
	--build-arg PYTHON_VERSION=3.8.16 \
	--build-arg USER_UID=$(id -u) \
	--build-arg USER_GID=$(id -g) \
	-f Dockerfile .
```
Resulting container's OS information is as follows
```
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

### Additional dependencies

```bash
$ pip freeze
astroid==2.14.2
attrs==22.2.0
aws-sam-translator==1.59.0
bcrypt==4.0.1
black==23.1.0
boto3==1.26.77
botocore==1.29.77
bump2version==1.0.1
certifi==2022.12.7
cffi==1.15.1
cfn-lint==0.73.2
charset-normalizer==3.0.1
click==8.1.3
cryptography==39.0.1
dill==0.3.6
distro==1.8.0
docker==6.0.1
docker-compose==1.29.2
dockerpty==0.4.1
docopt==0.6.2
idna==3.4
iniconfig==2.0.0
isort==5.12.0
jmespath==1.0.1
jschema-to-python==1.2.3
jsonpatch==1.32
jsonpickle==3.0.1
jsonpointer==2.3
jsonschema==3.2.0
junit-xml==1.9
lark==1.1.5
lazy-object-proxy==1.9.0
mccabe==0.7.0
mypy-extensions==1.0.0
networkx==3.0
packaging==23.0
paramiko==3.0.0
pathspec==0.11.0
pbr==5.11.1
platformdirs==3.0.0
pluggy==1.0.0
pycparser==2.21
pydantic==1.10.5
pydocstyle==6.3.0
pylint==2.16.2
pylint-pytest==1.1.2
PyNaCl==1.5.0
pyrsistent==0.19.3
pytest==7.2.1
python-dateutil==2.8.2
python-dotenv==0.21.1
python-hcl2==4.3.0
PyYAML==5.4.1
requests==2.28.2
s3transfer==0.6.0
sarif-om==1.0.4
six==1.16.0
snowballstemmer==2.2.0
texttable==1.6.7
tftest==1.8.2
tomlkit==0.11.6
typing_extensions==4.4.0
urllib3==1.26.14
websocket-client==0.59.0
wrapt==1.14.1
```

**Comment by degustaf** [comment] 2023-06-13 12:16
Is this strictly a Python3.12 issue? Do you get the same crash with 3.11?

**Comment by Pierre-Sassoulas** [comment] 2023-06-13 12:19
Cannot reproduce either, either on main nor 2.16.2. I was going to suggest trying with pylint 2.17.5 like @jacobtylerwalls.  right now pylint is not ready for python 3.12 (astroid is going to crash in python 3.12 no matter what if there is type parameters in the code), but we appreciate any bug report for 3.12.

**Comment by jacobtylerwalls** [comment] 2023-06-13 12:21
I tried to reproduce on 3.12 and pylint ran cleanly, so I think to repro I'll need to get the entire project source.

**Comment by ferricoxide** [comment] 2023-06-13 12:33
Oh. Wow. That was a quick set of replies.

At any rate, the project that I'm using GitHub actions through is (actually, "will be", since [my PR](https://github.com/ferricoxide/ash-linux-formula/tree/Issue_409) is what's adding the currently-failing `pylint`) [plus3it/ash-linux-formula](https://github.com/plus3it/ash-linux-formula/).  Let me know if these links address the:

> &hellip; I think to repro I'll need to get the entire project source.

Statement.

Regardless, I'm more than happy to do any additional troubleshooting tasks, etc.

**Comment by ferricoxide** [comment] 2023-06-13 12:40
> In the meantime, would you be willing to retry against the latest stable versions of pylint and astroid?

Yes. We use inherited GitHub actions (that we maintain in a separate project), so, I'll need to untangle pinning the requisite versions. I'll start digging into that, directly.

**Comment by ferricoxide** [comment] 2023-06-13 13:07
Ok, so updating my execution-environment (container) such that:
```bash
$ pylint --version
pylint 2.17.4
astroid 2.15.5
Python 3.12.0b1 (main, May 24 2023, 00:17:11) [GCC 8.3.0]
```
Seems to make the astroid-crash go away. So, not a Py 3.12 issue.

**Comment by Pierre-Sassoulas** [comment] 2023-06-13 13:27
I'm closing it as fixed in latest version then, thank you for opening the issue 👍

**Closed by Pierre-Sassoulas** 2023-06-13 13:27 UTC
Labels: Needs reproduction :mag:, Crash 💥

**Comment by ferricoxide** [comment] 2023-06-13 13:30
Thank y'all for the speedy (and gentle) response. :)
