### ISSUE TITLE
Crash with python 3.12 alpha

### ISSUE THREAD

**Issue by hannob** [pylint-dev/pylint#8588] opened 2023-04-18 07:14 UTC
### Bug description

When parsing the following file:

```python
def test():
 return
setattr(test, '_xx', True)
print(locals().items())
```

pylint crashed with a ``AstroidError`` and with the following stacktrace:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/astroid/decorators.py", line 143, in raise_if_nothing_inferred
    yield next(generator)
          ^^^^^^^^^^^^^^^
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/pylint/lint/pylinter.py", line 811, in _lint_file
    check_astroid_module(module)
  File "/usr/local/lib/python3.12/site-packages/pylint/lint/pylinter.py", line 1085, in check_astroid_module
    retval = self._check_astroid_module(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pylint/lint/pylinter.py", line 1135, in _check_astroid_module
    walker.walk(node)
  File "/usr/local/lib/python3.12/site-packages/pylint/utils/ast_walker.py", line 94, in walk
    self.walk(child)
  File "/usr/local/lib/python3.12/site-packages/pylint/utils/ast_walker.py", line 94, in walk
    self.walk(child)
  File "/usr/local/lib/python3.12/site-packages/pylint/utils/ast_walker.py", line 94, in walk
    self.walk(child)
  File "/usr/local/lib/python3.12/site-packages/pylint/utils/ast_walker.py", line 91, in walk
    callback(astroid)
  File "/usr/local/lib/python3.12/site-packages/pylint/checkers/base/basic_checker.py", line 713, in visit_call
    if utils.is_terminating_func(node):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pylint/checkers/utils.py", line 2202, in is_terminating_func
    return True
           ^^^^
  File "/usr/local/lib/python3.12/site-packages/astroid/nodes/node_ng.py", line 171, in infer
    yield from self._infer(context=context, **kwargs)
  File "/usr/local/lib/python3.12/site-packages/astroid/decorators.py", line 143, in raise_if_nothing_inferred
    yield next(generator)
          ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/astroid/decorators.py", line 120, in wrapped
    yielded.add(ares)
  File "/usr/local/lib/python3.12/site-packages/astroid/inference.py", line 358, in infer_attribute
    for owner in self.expr.infer(context):
  File "/usr/local/lib/python3.12/site-packages/astroid/nodes/node_ng.py", line 184, in infer
    for i, result in enumerate(self._infer(context=context, **kwargs)):
  File "/usr/local/lib/python3.12/site-packages/astroid/decorators.py", line 149, in raise_if_nothing_inferred
    raise InferenceError(
astroid.exceptions.InferenceError: StopIteration raised without any error information.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/pylint/lint/pylinter.py", line 775, in _lint_files
    self._lint_file(fileitem, module, check_astroid_module)
  File "/usr/local/lib/python3.12/site-packages/pylint/lint/pylinter.py", line 813, in _lint_file
    raise astroid.AstroidError from e
astroid.exceptions.AstroidError


### Configuration

```ini
This happens with pylint running in a python 3.12 (aka alpha) environment, e.g. when using github actions with python 3.12-dev.

It can be reproduced within docker:

docker run --rm -ti python:3.12.0a7 /bin/bash
echo -en "def test():\n return\nsetattr(test, '_xx', True)\nprint(locals().items())\n" > test.py
pip install pylint
pylint test.py
```
```


### Command used

```shell
pylint test.py
```

### Pylint output

```shell
/test.py:1:0: F0002: test.py: Fatal error while checking 'test.py'. Please open an issue in our bug tracker so we address this. There is a pre-filled template that you can use in '/root/.cache/pylint/pylint-crash-2023-04-18-07-13-47.txt'. (astroid-error)
```

### Expected behavior

no crash

### Pylint version

```shell
pylint 2.17.2
astroid 2.15.3
Python 3.12.0a7 (main, Apr 12 2023, 14:13:09) [GCC 10.2.1 20210110]
```

### OS / Environment

Debian image with python 3.12

**Comment by hartwork** [comment] 2023-04-18 12:15
I believe even this subset is enough to reproduce, I see the same traceback with Python 3.12a7 (but not 3.11.3):
```python
print(locals().items())
```

**Comment by jacobtylerwalls** [comment] 2023-05-18 15:12
Thanks for the report. This is an upstream issue in CPython, fixed in their main branch (see https://github.com/pylint-dev/pylint/issues/8695#issuecomment-1553151207). Closing as duplicate of #8695.

**Closed by jacobtylerwalls** 2023-05-18 15:12 UTC
Labels: Crash 💥, Needs investigation 🔬, python 3.12
