### ISSUE TITLE
AttributeError: module 'pylint.interfaces' has no attribute 'IAstroidChecker'

### ISSUE THREAD

**Issue by vinothgitkumar** [pylint-dev/pylint#9102] opened 2023-10-03 12:07 UTC
### Bug description

```python
While trying to install pylint-airflow(pip install pylint-airflow) it throws the below error in my GitHub action.

Error:
implements = interfaces.IAstroidChecker
AttributeError: module 'pylint.interfaces' has no attribute 'IAstroidChecker'
```

### Configuration

```ini
[FORMAT]
max-line-length=240

[MESSAGES CONTROL]
disable=imports

[OUTPUT]
output-format=json:output.json,colorized

[THRESHOLD]
fail-under=0
```

### Command used

```shell
My Github Action:

name: Pylinting
run: |
pip install pylint-airflow
pylint --load-plugins=pylint_airflow dags/digest/*.py
```

### Pylint output

```python
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.18/x64/bin/pylint", line 8, in <module>
    sys.exit(run_pylint())
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/pylint/__init__.py", line 34, in run_pylint
    PylintRun(argv or sys.argv[1:])
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/pylint/lint/run.py", line 155, in __init__
    linter.load_plugin_modules(self._plugins)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/pylint/lint/pylinter.py", line 380, in load_plugin_modules
    module = astroid.modutils.load_module_from_name(modname)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/astroid/modutils.py", line 194, in load_module_from_name
    module = importlib.import_module(dotted_name)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/pylint_airflow/__init__.py", line 5, in <module>
    from pylint_airflow.checkers import register_checkers as register
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/pylint_airflow/checkers/__init__.py", line 3, in <module>
    from pylint_airflow.checkers.dag import DagChecker
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/pylint_airflow/checkers/dag.py", line 15, in <module>
    class DagChecker(checkers.BaseChecker):
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/pylint_airflow/checkers/dag.py", line 18, in DagChecker
    __implements__ = interfaces.IAstroidChecker
AttributeError: module 'pylint.interfaces' has no attribute 'IAstroidChecker'
Error: Process completed with exit code 1.
```

### Expected behavior

No Error

### Pylint version

```shell
pylint-airflow 0.1.0a1
```

**Comment by DanielNoord** [comment] 2023-10-03 12:11
Duplicate of https://github.com/pylint-dev/pylint/issues/9094.

`pylint-airflow` will have to update their code to become compatible with `3.x` again. As said in that issue, we had to remove this it was not working as expected and based on a very old rejected PEP.

**Closed by DanielNoord** 2023-10-03 12:11 UTC
Labels: Needs triage :inbox_tray:
