### ISSUE TITLE
Crash when encountering "start=" in an enumerate-for-loop

### ISSUE THREAD

**Issue by MauererM** [pylint-dev/pylint#9272] opened 2023-11-29 14:44 UTC
### Bug description

When parsing the following ``analysis.py``:

profit_src/analysis.py:107:45: W0511: Todo: The start=n here seems to crash Pylint... (fixme)
Exception on node <For l.107 at 0x7fb8087909d0> in file '/home/mario/git/profit/profit_src/analysis.py'
Traceback (most recent call last):
  File "/home/mario/.local/lib/python3.8/site-packages/pylint/utils/ast_walker.py", line 91, in walk
    callback(astroid)
  File "/home/mario/.local/lib/python3.8/site-packages/pylint/checkers/refactoring/refactoring_checker.py", line 692, in visit_for
    self._check_unnecessary_list_index_lookup(node)
  File "/home/mario/.local/lib/python3.8/site-packages/pylint/checkers/refactoring/refactoring_checker.py", line 2216, in _check_unnecessary_list_index_lookup
    has_start_arg, confidence = self._enumerate_with_start(node)
  File "/home/mario/.local/lib/python3.8/site-packages/pylint/checkers/refactoring/refactoring_checker.py", line 2348, in _enumerate_with_start
    start_val, confidence = self._get_start_value(keyword.value)
  File "/home/mario/.local/lib/python3.8/site-packages/pylint/checkers/refactoring/refactoring_checker.py", line 2362, in _get_start_value
    start_val = inferred.value if inferred else None
  File "/home/mario/.local/lib/python3.8/site-packages/astroid/bases.py", line 140, in __getattr__
    return getattr(self._proxied, name)
AttributeError: 'ClassDef' object has no attribute 'value'
profit_src/analysis.py:1:0: F0002: profit_src/analysis.py: Fatal error while checking 'profit_src/analysis.py'. Please open an issue in our bug tracker so we address this. There is a pre-filled template that you can use in '/home/mario/.cache/pylint/pylint-crash-2023-11-29-15-32-30.txt'. (astroid-error)

The crash seems to happen around this area in the code, specifically, the start=n: 

def calc_moving_avg(xlist, ylist, winlen):
    """Calculates the moving-average of a XY data-set. The correspondingly filtered tuple is returned
    (which might be of a shorter length, if winlen > 1) ==> Values are only added, once the moving window is full of
    samples.
    If the list is shorter than the window, the average of the list is returned, together with the last entry in xlist
    :param xlist: List of x-values
    :param ylist: List of to-be-filtered y-values
    :param winlen: Length of the window, must be >= 1
    :return: tuple of filtered x,y values
    """
    if winlen < 1:
        raise RuntimeError("Window length of moving average filter must be >= 1")
    if len(xlist) != len(ylist):
        raise RuntimeError("X, Y lists of moving-avg filter must be of same length")

    # make sure the winlen is an integer:
    n = int(round(winlen, 0))
    if n == 1:
        return xlist, ylist

    # If the data is shorter than the window: simply return the averaged ylist
    if len(xlist) <= n:
        yfilt = sum(ylist) / len(ylist)
        # Get the middle index of the list:
        mididx = int(round(len(xlist) / 2.0)) - 1
        xfilt = xlist[mididx]
        return xfilt, yfilt

    # Window shorter than data lists:
    xfilt = []
    yfilt = []
    # Middle index:
    mididx = int(round(n / 2.0))
    for i, _ in enumerate(ylist, start=n):  # Todo: The start=n here seems to crash Pylint...
        if i == len(ylist) + 1:
            break
        win = ylist[i - n:i]
        avg = sum(win) / n
        xfilt.append(xlist[i - n + mididx - 1])
        yfilt.append(avg)
    return xfilt, yfilt

```

### Command used

```shell
pylint a.py
```

### Pylint output

<details open>
    <summary>
        pylint crashed with a ``AstroidError`` and with the following stacktrace:
    </summary>

```python
Traceback (most recent call last):
  File "/home/mario/.local/lib/python3.8/site-packages/pylint/lint/pylinter.py", line 788, in _lint_file
    check_astroid_module(module)
  File "/home/mario/.local/lib/python3.8/site-packages/pylint/lint/pylinter.py", line 1017, in check_astroid_module
    retval = self._check_astroid_module(
  File "/home/mario/.local/lib/python3.8/site-packages/pylint/lint/pylinter.py", line 1069, in _check_astroid_module
    walker.walk(node)
  File "/home/mario/.local/lib/python3.8/site-packages/pylint/utils/ast_walker.py", line 94, in walk
    self.walk(child)
  File "/home/mario/.local/lib/python3.8/site-packages/pylint/utils/ast_walker.py", line 94, in walk
    self.walk(child)
  File "/home/mario/.local/lib/python3.8/site-packages/pylint/utils/ast_walker.py", line 91, in walk
    callback(astroid)
  File "/home/mario/.local/lib/python3.8/site-packages/pylint/checkers/refactoring/refactoring_checker.py", line 692, in visit_for
    self._check_unnecessary_list_index_lookup(node)
  File "/home/mario/.local/lib/python3.8/site-packages/pylint/checkers/refactoring/refactoring_checker.py", line 2216, in _check_unnecessary_list_index_lookup
    has_start_arg, confidence = self._enumerate_with_start(node)
  File "/home/mario/.local/lib/python3.8/site-packages/pylint/checkers/refactoring/refactoring_checker.py", line 2348, in _enumerate_with_start
    start_val, confidence = self._get_start_value(keyword.value)
  File "/home/mario/.local/lib/python3.8/site-packages/pylint/checkers/refactoring/refactoring_checker.py", line 2362, in _get_start_value
    start_val = inferred.value if inferred else None
  File "/home/mario/.local/lib/python3.8/site-packages/astroid/bases.py", line 140, in __getattr__
    return getattr(self._proxied, name)
AttributeError: 'ClassDef' object has no attribute 'value'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/mario/.local/lib/python3.8/site-packages/pylint/lint/pylinter.py", line 752, in _lint_files
    self._lint_file(fileitem, module, check_astroid_module)
  File "/home/mario/.local/lib/python3.8/site-packages/pylint/lint/pylinter.py", line 790, in _lint_file
    raise astroid.AstroidError from e
astroid.exceptions.AstroidError

```

</details>

### Expected behavior

No crash.

### Pylint version

```shell
pylint 3.0.2
astroid 3.0.1
Python 3.8.10 (default, Nov 22 2023, 10:22:35) 
[GCC 9.4.0]
```

### OS / Environment

linux (Linux)

**Comment by nickdrozd** [comment] 2023-11-29 15:24
Short reproducer:

```python
def calc_moving_avg(ylist, winlen):
    for _, _ in enumerate(ylist, start = int(winlen)):
        pass
```

**Comment by nickdrozd** [comment] 2023-11-29 15:25
Duplicate of https://github.com/pylint-dev/pylint/issues/9078

**Closed by nickdrozd** 2023-11-29 15:25 UTC
Labels: Crash 💥
