### ISSUE TITLE
Class template variable is not recognized in method body

### ISSUE THREAD

**Issue by jolaf** [pylint-dev/pylint#9848] opened 2024-08-03 01:58 UTC
### Bug description

```python
from typing import cast

class A[T]:
    @staticmethod
    def f() -> None:
        cast(T, None)
```

### Command used

```shell
pylint test.py
```

### Pylint output

```python
************* Module test
test.py:6: [E0602(undefined-variable), A.f] Undefined variable 'T'
```

### Expected behavior

No error.

### Pylint version

```shell
pylint 3.2.6
astroid 3.2.4
Python 3.12.3 (main, Jul 31 2024, 17:43:48) [GCC 13.2.0]
```

### OS / Environment

Ubuntu 24.04

**Comment by jacobtylerwalls** [comment] 2024-08-17 16:46
Duplicate of #9335

**Closed by jacobtylerwalls** 2024-08-17 16:46 UTC
Labels: Needs triage :inbox_tray:
