### ISSUE TITLE
Failure with: TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by hpenedones** [pylint-dev/pylint#9107] opened 2023-10-03 14:54 UTC
### Bug description

```python
We have a GitHub action running pylint on our code, and a recent update of pylint, caused failures (it is crashing and returning exit code 123). You can see the full logs here:

https://github.com/inductiva/inductiva/actions/runs/6391944728/job/17351304614?pr=734
```

### Command used

```shell
Run find . -type f -not -path "./third_party/*" -name '*.py' | xargs pylint
```

### Pylint output

```python
Exception on node <AssignName.PRESSURE l.235 at 0x7fc9ca7116d0> in file '/home/runner/work/inductiva/inductiva/inductiva/fluids/post_processing/openfoam.py'
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/pylint/utils/ast_walker.py", line 91, in walk
    callback(astroid)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/pylint/checkers/base/name_checker/checker.py", line 488, in visit_assignname
    if utils.is_enum_member(node) or utils.is_assign_name_annotated_with(
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/pylint/checkers/utils.py", line 2284, in is_enum_member
    enum_member_objects = frame.locals.get("__members__")[0].items
TypeError: 'NoneType' object is not subscriptable
Exception on node <AssignName.HIGH l.12 at 0x7fc9ca0a1280> in file '/home/runner/work/inductiva/inductiva/inductiva/fluids/dam_break/dam_break.py'
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/pylint/utils/ast_walker.py", line 91, in walk
    callback(astroid)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/pylint/checkers/base/name_checker/checker.py", line 488, in visit_assignname
    if utils.is_enum_member(node) or utils.is_assign_name_annotated_with(
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/pylint/checkers/utils.py", line 2284, in is_enum_member
    enum_member_objects = frame.locals.get("__members__")[0].items
TypeError: 'NoneType' object is not subscriptable
Exception on node <AssignName.HIGH l.24 at 0x7fc9d15aa760> in file '/home/runner/work/inductiva/inductiva/inductiva/fluids/fluid_tank/fluid_tank.py'
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/pylint/utils/ast_walker.py", line 91, in walk
    callback(astroid)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/pylint/checkers/base/name_checker/checker.py", line 488, in visit_assignname
    if utils.is_enum_member(node) or utils.is_assign_name_annotated_with(
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/pylint/checkers/utils.py", line 2284, in is_enum_member
    enum_member_objects = frame.locals.get("__members__")[0].items
TypeError: 'NoneType' object is not subscriptable
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/pylint/lint/pylinter.py", line 831, in _check_file
    check_astroid_module(ast_node)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/pylint/lint/pylinter.py", line 1017, in check_astroid_module
    retval = self._check_astroid_module(
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/pylint/lint/pylinter.py", line 1069, in _check_astroid_module
    walker.walk(node)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/pylint/utils/ast_walker.py", line 94, in walk
    self.walk(child)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/pylint/utils/ast_walker.py", line 94, in walk
    self.walk(child)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/pylint/utils/ast_walker.py", line 94, in walk
    self.walk(child)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/pylint/utils/ast_walker.py", line 91, in walk
    callback(astroid)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/pylint/checkers/base/name_checker/checker.py", line 488, in visit_assignname
    if utils.is_enum_member(node) or utils.is_assign_name_annotated_with(
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/pylint/checkers/utils.py", line 2284, in is_enum_member
    enum_member_objects = frame.locals.get("__members__")[0].items
TypeError: 'NoneType' object is not subscriptable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/concurrent/futures/process.py", line 239, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/concurrent/futures/process.py", line 198, in _process_chunk
    return [fn(*args) for args in chunk]
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/concurrent/futures/process.py", line 198, in <listcomp>
    return [fn(*args) for args in chunk]
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/pylint/lint/parallel.py", line 79, in _worker_check_single_file
    _worker_linter.check_single_file_item(file_item)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/pylint/lint/pylinter.py", line 740, in check_single_file_item
    self._check_file(self.get_ast, check_astroid_module, file)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/pylint/lint/pylinter.py", line 833, in _check_file
    raise astroid.AstroidError from e
astroid.exceptions.AstroidError
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.18/x64/bin/pylint", line 8, in <module>
    sys.exit(run_pylint())
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/pylint/__init__.py", line 34, in run_pylint
    PylintRun(argv or sys.argv[1:])
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/pylint/lint/run.py", line 211, in __init__
    linter.check(args)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/pylint/lint/pylinter.py", line 679, in check
    check_parallel(
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/pylint/lint/parallel.py", line 153, in check_parallel
    for (
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/concurrent/futures/process.py", line 484, in _chain_from_iterable_of_lists
    for element in iterable:
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/concurrent/futures/_base.py", line 619, in result_iterator
    yield fs.pop().result()
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
astroid.exceptions.AstroidError
Error: Process completed with exit code 123.
```

### Expected behavior

We would expect pylint not to crash, and either return some warnings about the code, or certify that everything is ok.

### Pylint version

```shell
pylint 3.0.0
```

### OS / Environment

Ubuntu
  22.04.3 LTS

  Image: ubuntu-22.04
  Version: 20230924.1.0

### Additional dependencies

```python
yapf pytest pytest-custom_exit_code toml
```

**Comment by mbyrnepr2** [comment] 2023-10-03 16:44
Thanks. Closing as duplicate of https://github.com/pylint-dev/pylint/issues/9100

**Closed** 2023-10-03 16:44 UTC
Labels: Needs triage :inbox_tray:
