### ISSUE TITLE
Incorrect linting with type parameters PEP695 (generic)

### ISSUE THREAD

**Issue by wookayin** [pylint-dev/pylint#9110] opened 2023-10-04 05:32 UTC
### Bug description

Python 3.12.0

Possibly sharing the same root cause as #9098 but I'm reporting as the behavior is different just in case (here no crashes, just incorrect results). It'd be great if pylint can support all the type parameters specification described in https://peps.python.org/pep-0695/.

```python
def constrained[T: (str, bytes)](argument: T) -> T:
    return argument
```

(EDIT: removed the second example in edit because it's not valid)

### Configuration

```ini
No pylintrc is used (under the default setting).
```

### Command used

```shell
pylint 695.py --disable=C0114,C0116

(Note: C0114, C0116 are missing docstrings)
```

### Pylint output

```python
************* Module 695
695.py:1:43: E0602: Undefined variable 'T' (undefined-variable)
695.py:1:49: E0602: Undefined variable 'T' (undefined-variable)
695.py:1:16: W0612: Unused variable 'T' (unused-variable)
```

### Expected behavior

There should be no E0602, W0612, E0602 warnings and errors. `T` in the parameter annotation is the generic type.

### Pylint version

```shell
pylint 3.0.0
astroid 3.0.0
Python 3.12.0 | packaged by conda-forge | (main, Oct  3 2023, 08:36:57) [Clang 15.0.7 ]
```

### OS / Environment

macOS and Linux

### Additional dependencies

```python
N/A
```

**Comment by DanielNoord** [comment] 2023-10-04 05:47
@jacobtylerwalls do we have any idea how hard it is to support the new typing syntax for the variables checker?

**Comment by jacobtylerwalls** [comment] 2023-10-04 11:01
I do think it's the same root cause as #9098. Not terribly difficult, just figuring out how to make assigned_stmts() return the correct thing. A few hours? (I'm traveling this week).

**Comment by jacobtylerwalls** [comment] 2023-10-15 15:14
Turns out this is a distinct fix from the crash. The crash can be fixed in astroid; the false positives can be fixed in pylint. Patches coming up.

**Closed** 2023-10-16 12:51 UTC
Labels: C: used-before-assignment, python 3.12
