### ISSUE TITLE
Crash - AstroidError under Python 3.12.0a7; raise_if_nothing_inferred

### ISSUE THREAD

**Issue by jnsnow** [pylint-dev/pylint#8804] opened 2023-06-28 22:24 UTC
### Bug description

Pylint 2.17.4 fatally crashes when checking the following minimal reproducer under Python 3.12.0a7:

```python
class Reproducer:
    def foo(self) -> None:
        return self.bar()

    def baz(self) -> None:
        return self.xyzzy()
```

Version information:

Other information:

I am seeing this crash on production code that checks fine under mypy/pylint from Python 3.7 through 3.11 inclusive; it's only under Python 3.12 that pylint alone crashes. This reproducer is as small as I could get it while still seeing the crash. I unfortunately couldn't find a minimal reproducer for code that I believed "should work"; the code in question that prompted this bug report can be found at https://gitlab.com/qemu-project/python-qemu-qmp/-/blob/main/qemu/qmp/protocol.py

(If you clone the repo and have Python 3.12 available and type "make check-tox", you should be able to see it fail on the production code for yourself.)

### Command used

```shell
`pylint reproducer.py`
```

### Pylint output

```shell
pylint crashed with a ``AstroidError`` and with the following stacktrace:

Traceback (most recent call last):
  File "/home/jsnow/src/qemu.qmp/.tox/py312/lib/python3.12/site-packages/astroid/decorators.py", line 143, in raise_if_nothing_inferred
    yield next(generator)
          ^^^^^^^^^^^^^^^
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jsnow/src/qemu.qmp/.tox/py312/lib/python3.12/site-packages/pylint/lint/pylinter.py", line 811, in _lint_file
    check_astroid_module(module)
  File "/home/jsnow/src/qemu.qmp/.tox/py312/lib/python3.12/site-packages/pylint/lint/pylinter.py", line 1085, in check_astroid_module
    retval = self._check_astroid_module(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jsnow/src/qemu.qmp/.tox/py312/lib/python3.12/site-packages/pylint/lint/pylinter.py", line 1135, in _check_astroid_module
    walker.walk(node)
  File "/home/jsnow/src/qemu.qmp/.tox/py312/lib/python3.12/site-packages/pylint/utils/ast_walker.py", line 94, in walk
    self.walk(child)
  File "/home/jsnow/src/qemu.qmp/.tox/py312/lib/python3.12/site-packages/pylint/utils/ast_walker.py", line 94, in walk
    self.walk(child)
  File "/home/jsnow/src/qemu.qmp/.tox/py312/lib/python3.12/site-packages/pylint/utils/ast_walker.py", line 94, in walk
    self.walk(child)
  [Previous line repeated 1 more time]
  File "/home/jsnow/src/qemu.qmp/.tox/py312/lib/python3.12/site-packages/pylint/utils/ast_walker.py", line 91, in walk
    callback(astroid)
  File "/home/jsnow/src/qemu.qmp/.tox/py312/lib/python3.12/site-packages/pylint/checkers/base/basic_checker.py", line 713, in visit_call
    if utils.is_terminating_func(node):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jsnow/src/qemu.qmp/.tox/py312/lib/python3.12/site-packages/pylint/checkers/utils.py", line 2202, in is_terminating_func
    return True
           ^^^^
  File "/home/jsnow/src/qemu.qmp/.tox/py312/lib/python3.12/site-packages/astroid/nodes/node_ng.py", line 171, in infer
    yield from self._infer(context=context, **kwargs)
  File "/home/jsnow/src/qemu.qmp/.tox/py312/lib/python3.12/site-packages/astroid/decorators.py", line 149, in raise_if_nothing_inferred
    raise InferenceError(
astroid.exceptions.InferenceError: StopIteration raised without any error information.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jsnow/src/qemu.qmp/.tox/py312/lib/python3.12/site-packages/pylint/lint/pylinter.py", line 775, in _lint_files
    self._lint_file(fileitem, module, check_astroid_module)
  File "/home/jsnow/src/qemu.qmp/.tox/py312/lib/python3.12/site-packages/pylint/lint/pylinter.py", line 813, in _lint_file
    raise astroid.AstroidError from e
astroid.exceptions.AstroidError
```
```


### Expected behavior

Pylint shouldn't crash.

### Pylint version

```shell
pylint 2.17.4
astroid 2.15.5
Python 3.12.0a7 (main, Apr  5 2023, 00:00:00) [GCC 13.0.1 20230401 (Red Hat 13.0.1-0)]
```

### OS / Environment

Fedora 38

**Comment by jacobtylerwalls** [comment] 2023-06-28 23:15
Thanks for the report. Duplicate of #8695 (fixed upstream in subsequent CPython releases). Keep the 3.12 issues coming! :-)

**Closed by jacobtylerwalls** 2023-06-28 23:15 UTC
Labels: Needs triage :inbox_tray:

**Comment by jnsnow** [comment] 2023-06-28 23:27
> Thanks for the report. Duplicate of #8695 (fixed upstream in subsequent CPython releases). Keep the 3.12 issues coming! :-)

Whoops, missed that one. I've upgraded to 0b3 and pylint is still eating dirt, but differently. Let me go back to the kitchen and cook up a new repro. :)

**Comment by jacobtylerwalls** [comment] 2023-06-28 23:29
Sounds good. (Make sure to be aware of #8782.)
