### ISSUE TITLE
deprecate typing.NamedTuple in favor of dataclasses

### ISSUE THREAD

**Issue by vapier** [pylint-dev/pylint#8657] opened 2023-05-04 20:07 UTC
### Current problem

when using Python 3.8+, typing.NamedTuple is archaic, and should be flagged for upgrading

### Desired solution

when typing.NamedTuple is seen, recommend using dataclasses instead

**Comment by DanielNoord** [comment] 2023-05-04 21:05
Closing as duplicate of https://github.com/pylint-dev/pylint/issues/8656

**Closed by DanielNoord** 2023-05-04 21:05 UTC
Labels: Needs triage :inbox_tray:
