### ISSUE TITLE
Regression(3.2): matplotlib.widgets.CheckButtons.get_status() is no longer recognized as a list

### ISSUE THREAD

**Issue by sam-s** [pylint-dev/pylint#9629] opened 2024-05-15 13:22 UTC
### Bug description

Starting with pylint 3.2, I get [`not-an-iterable`](https://pylint.readthedocs.io/en/latest/user_guide/messages/error/not-an-iterable.html) and [`unsubscriptable-object`](https://pylint.readthedocs.io/en/latest/user_guide/messages/error/unsubscriptable-object.html) for the return value of [`matplotlib.widgets.CheckButtons.get_status()`](https://matplotlib.org/stable/api/widgets_api.html#matplotlib.widgets.CheckButtons.get_status).

Code:
```
"https://github.com/pylint-dev/pylint/issues/9629"

import matplotlib.pyplot as plt
from matplotlib.widgets import CheckButtons

_figure, axes = plt.subplots()
buttons = CheckButtons(axes, ["a","b"])
print("".join(f"_{v}" for v in buttons.get_status()))  # not-an-iterable
print(buttons.get_status()[0])                         # unsubscriptable-object
```

### Command used

```shell
pylint a.py
```

### Pylint output

```python
a.py:8:31: E1133: Non-iterable value buttons.get_status() is used in an iterating context (not-an-iterable)
a.py:9:6: E1136: Value 'buttons.get_status()' is unsubscriptable (unsubscriptable-object)
```

### Expected behavior

no diagnostics, like in 3.1

### Pylint version

```shell
pylint 3.2.0
astroid 3.2.0
Python 3.12.1 | packaged by conda-forge | (main, Dec 23 2023, 07:53:56) [MSC v.1937 64 bit (AMD64)]
```

### OS / Environment

windows

**Comment by jacobtylerwalls** [comment] 2024-05-15 14:18
Thanks for the report. Duplicate of #9626. I'll update the title to make that more clear.

Stay tuned for a patch release of pylint in the next few days.

**Closed by jacobtylerwalls** 2024-05-15 14:18 UTC
Labels: Needs triage :inbox_tray:
