### ISSUE TITLE
Maximum recursion depth exceeded with ray remote

### ISSUE THREAD

**Issue by cread** [pylint-dev/pylint#8565] opened 2023-04-11 18:29 UTC
### Bug description

We get a `RecursionError: maximum recursion depth exceeded while calling a Python object` with this code sample:

```python
import ray

def function(*args):
    return args

def pylint_crash(*args):
    as_remote = ray.remote(max_retries=3, num_cpus=1)(function)
    object_refs = []
    for arg in args:
        object_refs.append(as_remote.remote(arg))
    num_ready = 0
    while num_ready < len(args):
        ray.wait(object_refs, num_returns=1, timeout=None)
        num_ready += 1
    return ray.get(object_refs)

if __name__ == "__main__":
    ray.init()
    print(pylint_crash("Hello", "World"))
```

### Command used

```shell
python pylint-ray-crash.py
```

### Pylint output

```shell
************* Module pylint-ray-crash
pylint-ray-crash.py:1:0: C0114: Missing module docstring (missing-module-docstring)
pylint-ray-crash.py:1:0: C0103: Module name "pylint-ray-crash" doesn't conform to snake_case naming style (invalid-name)
pylint-ray-crash.py:4:0: C0116: Missing function or method docstring (missing-function-docstring)
pylint-ray-crash.py:8:0: C0116: Missing function or method docstring (missing-function-docstring)
Exception on node <Call l.15 at 0x7fb4bf8c9e10> in file '/tmp/pylint-issue/pylint-ray-crash.py'
Traceback (most recent call last):
  File "/tmp/pylint-issue/pylint-env/lib/python3.10/site-packages/astroid/decorators.py", line 143, in raise_if_nothing_inferred
    yield next(generator)
  File "/tmp/pylint-issue/pylint-env/lib/python3.10/site-packages/astroid/decorators.py", line 107, in wrapped
    if context.push(node):
RecursionError: maximum recursion depth exceeded

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/pylint-issue/pylint-env/lib/python3.10/site-packages/pylint/utils/ast_walker.py", line 91, in walk
    callback(astroid)
  File "/tmp/pylint-issue/pylint-env/lib/python3.10/site-packages/pylint/checkers/base/basic_checker.py", line 713, in visit_call
    if utils.is_terminating_func(node):
  File "/tmp/pylint-issue/pylint-env/lib/python3.10/site-packages/pylint/checkers/utils.py", line 2197, in is_terminating_func
    for inferred in node.func.infer():
  File "/tmp/pylint-issue/pylint-env/lib/python3.10/site-packages/astroid/nodes/node_ng.py", line 171, in infer
    yield from self._infer(context=context, **kwargs)
  File "/tmp/pylint-issue/pylint-env/lib/python3.10/site-packages/astroid/decorators.py", line 157, in raise_if_nothing_inferred
    yield from generator
  File "/tmp/pylint-issue/pylint-env/lib/python3.10/site-packages/astroid/decorators.py", line 112, in wrapped
    for res in _func(node, context, **kwargs):
  File "/tmp/pylint-issue/pylint-env/lib/python3.10/site-packages/astroid/inference.py", line 358, in infer_attribute
    for owner in self.expr.infer(context):
  File "/tmp/pylint-issue/pylint-env/lib/python3.10/site-packages/astroid/nodes/node_ng.py", line 184, in infer
    for i, result in enumerate(self._infer(context=context, **kwargs)):
  File "/tmp/pylint-issue/pylint-env/lib/python3.10/site-packages/astroid/decorators.py", line 157, in raise_if_nothing_inferred
    yield from generator
  File "/tmp/pylint-issue/pylint-env/lib/python3.10/site-packages/astroid/decorators.py", line 112, in wrapped
    for res in _func(node, context, **kwargs):
  File "/tmp/pylint-issue/pylint-env/lib/python3.10/site-packages/astroid/bases.py", line 177, in _infer_stmts
    for inf in stmt.infer(context=context):
  File "/tmp/pylint-issue/pylint-env/lib/python3.10/site-packages/astroid/nodes/node_ng.py", line 184, in infer
    for i, result in enumerate(self._infer(context=context, **kwargs)):
  File "/tmp/pylint-issue/pylint-env/lib/python3.10/site-packages/astroid/decorators.py", line 157, in raise_if_nothing_inferred
    yield from generator
  File "/tmp/pylint-issue/pylint-env/lib/python3.10/site-packages/astroid/decorators.py", line 112, in wrapped
    for res in _func(node, context, **kwargs):
  File "/tmp/pylint-issue/pylint-env/lib/python3.10/site-packages/astroid/bases.py", line 177, in _infer_stmts
    for inf in stmt.infer(context=context):
  File "/tmp/pylint-issue/pylint-env/lib/python3.10/site-packages/astroid/nodes/node_ng.py", line 184, in infer
    for i, result in enumerate(self._infer(context=context, **kwargs)):
  File "/tmp/pylint-issue/pylint-env/lib/python3.10/site-packages/astroid/decorators.py", line 157, in raise_if_nothing_inferred
    yield from generator
  File "/tmp/pylint-issue/pylint-env/lib/python3.10/site-packages/astroid/decorators.py", line 112, in wrapped
    for res in _func(node, context, **kwargs):
  File "/tmp/pylint-issue/pylint-env/lib/python3.10/site-packages/astroid/inference.py", line 279, in infer_call
    yield from callee.infer_call_result(caller=self, context=callcontext)
  File "/tmp/pylint-issue/pylint-env/lib/python3.10/site-packages/astroid/bases.py", line 322, in infer_call_result
    for res in node.infer_call_result(caller, context):
  File "/tmp/pylint-issue/pylint-env/lib/python3.10/site-packages/astroid/bases.py", line 322, in infer_call_result
    for res in node.infer_call_result(caller, context):
  File "/tmp/pylint-issue/pylint-env/lib/python3.10/site-packages/astroid/bases.py", line 322, in infer_call_result
    for res in node.infer_call_result(caller, context):
  [Previous line repeated 947 more times]
  File "/tmp/pylint-issue/pylint-env/lib/python3.10/site-packages/astroid/bases.py", line 319, in infer_call_result
    for node in self._proxied.igetattr("__call__", context):
  File "/tmp/pylint-issue/pylint-env/lib/python3.10/site-packages/astroid/nodes/scoped_nodes/scoped_nodes.py", line 2655, in igetattr
    inferred._proxied.getattr("__get__", context)
  File "/tmp/pylint-issue/pylint-env/lib/python3.10/site-packages/astroid/nodes/scoped_nodes/scoped_nodes.py", line 2563, in getattr
    values += self._metaclass_lookup_attribute(name, context)
  File "/tmp/pylint-issue/pylint-env/lib/python3.10/site-packages/astroid/nodes/scoped_nodes/scoped_nodes.py", line 2587, in _metaclass_lookup_attribute
    attrs.update(set(cls_attributes))
  File "/tmp/pylint-issue/pylint-env/lib/python3.10/site-packages/astroid/nodes/scoped_nodes/scoped_nodes.py", line 2592, in _get_attribute_from_metaclass
    attrs = cls.getattr(name, context=context, class_context=True)
  File "/tmp/pylint-issue/pylint-env/lib/python3.10/site-packages/astroid/nodes/scoped_nodes/scoped_nodes.py", line 2563, in getattr
    values += self._metaclass_lookup_attribute(name, context)
  File "/tmp/pylint-issue/pylint-env/lib/python3.10/site-packages/astroid/nodes/scoped_nodes/scoped_nodes.py", line 2583, in _metaclass_lookup_attribute
    metaclass = self.metaclass(context=context)
  File "/tmp/pylint-issue/pylint-env/lib/python3.10/site-packages/astroid/nodes/scoped_nodes/scoped_nodes.py", line 2869, in metaclass
    return self._find_metaclass(context=context)
  File "/tmp/pylint-issue/pylint-env/lib/python3.10/site-packages/astroid/nodes/scoped_nodes/scoped_nodes.py", line 2851, in _find_metaclass
    klass = self.declared_metaclass(context=context)
  File "/tmp/pylint-issue/pylint-env/lib/python3.10/site-packages/astroid/nodes/scoped_nodes/scoped_nodes.py", line 2823, in declared_metaclass
    for baseobj in base.infer(context=context):
  File "/tmp/pylint-issue/pylint-env/lib/python3.10/site-packages/astroid/nodes/node_ng.py", line 184, in infer
    for i, result in enumerate(self._infer(context=context, **kwargs)):
  File "/tmp/pylint-issue/pylint-env/lib/python3.10/site-packages/astroid/decorators.py", line 153, in raise_if_nothing_inferred
    raise InferenceError(
  File "/tmp/pylint-issue/pylint-env/lib/python3.10/site-packages/astroid/exceptions.py", line 276, in __init__
    super().__init__(message, **kws)
RecursionError: maximum recursion depth exceeded while calling a Python object
pylint-ray-crash.py:1:0: F0002: pylint-ray-crash.py: Fatal error while checking 'pylint-ray-crash.py'. Please open an issue in our bug tracker so we address this. There is a pre-filled template that you can use in '/home/cread/.cache/pylint/pylint-crash-2023-04-11-13-28-13.txt'. (astroid-error)
```

### Expected behavior

No errors.

### Pylint version

```shell
pylint 2.17.2
astroid 2.15.2
Python 3.10.2
```

### OS / Environment

Ubuntu 20.04

**Comment by jacobtylerwalls** [comment] 2023-04-12 11:58
Thanks for the reproducer! Duplicate of pylint-dev/astroid#1939, but I'll cross-post there with your helpful reproducer.

**Closed by jacobtylerwalls** 2023-04-12 11:58 UTC
Labels: Crash 💥, Needs investigation 🔬
