### ISSUE TITLE
Pylint crashes with AstroidError on creating a custom base model with SQLAlchemy

### ISSUE THREAD

**Issue by winstxnhdw** [pylint-dev/pylint#8573] opened 2023-04-13 06:10 UTC
### Bug description

```python
from sqlalchemy import Column, Integer
from sqlalchemy.orm import DeclarativeBase, declared_attr


class Base(DeclarativeBase):
    """
    Summary
    -------
    Base class for all models
    """
    id =  Column(Integer, primary_key=True)

    @declared_attr.directive
    def __tablename__(self) -> str:
        """
        Summary
        -------
        sets the table name
        """
        return self.__class__.__name__.lower()

```

pylint crashed with a ``AstroidError`` and with the following stacktrace:
```
Traceback (most recent call last):
  File "/home/winston/.vscode/extensions/ms-python.pylint-2023.4.0/bundled/libs/pylint/lint/pylinter.py", line 798, in _lint_file
    check_astroid_module(module)
  File "/home/winston/.vscode/extensions/ms-python.pylint-2023.4.0/bundled/libs/pylint/lint/pylinter.py", line 1067, in check_astroid_module
    retval = self._check_astroid_module(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/winston/.vscode/extensions/ms-python.pylint-2023.4.0/bundled/libs/pylint/lint/pylinter.py", line 1117, in _check_astroid_module
    walker.walk(node)
  File "/home/winston/.vscode/extensions/ms-python.pylint-2023.4.0/bundled/libs/pylint/utils/ast_walker.py", line 94, in walk
    self.walk(child)
  File "/home/winston/.vscode/extensions/ms-python.pylint-2023.4.0/bundled/libs/pylint/utils/ast_walker.py", line 94, in walk
    self.walk(child)
  File "/home/winston/.vscode/extensions/ms-python.pylint-2023.4.0/bundled/libs/pylint/utils/ast_walker.py", line 91, in walk
    callback(astroid)
  File "/home/winston/.vscode/extensions/ms-python.pylint-2023.4.0/bundled/libs/pylint/checkers/classes/special_methods_checker.py", line 183, in visit_functiondef
    inferred = _safe_infer_call_result(node, node)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/winston/.vscode/extensions/ms-python.pylint-2023.4.0/bundled/libs/pylint/checkers/classes/special_methods_checker.py", line 42, in _safe_infer_call_result
    value = next(inferit)
            ^^^^^^^^^^^^^
  File "/home/winston/.vscode/extensions/ms-python.pylint-2023.4.0/bundled/libs/astroid/nodes/scoped_nodes/scoped_nodes.py", line 1733, in infer_call_result
    yield from returnnode.value.infer(context)
  File "/home/winston/.vscode/extensions/ms-python.pylint-2023.4.0/bundled/libs/astroid/nodes/node_ng.py", line 171, in infer
    yield from self._infer(context=context, **kwargs)
  File "/home/winston/.vscode/extensions/ms-python.pylint-2023.4.0/bundled/libs/astroid/decorators.py", line 142, in raise_if_nothing_inferred
    yield next(generator)
          ^^^^^^^^^^^^^^^
  File "/home/winston/.vscode/extensions/ms-python.pylint-2023.4.0/bundled/libs/astroid/decorators.py", line 111, in wrapped
    for res in _func(node, context, **kwargs):
  File "/home/winston/.vscode/extensions/ms-python.pylint-2023.4.0/bundled/libs/astroid/inference.py", line 270, in infer_call
    for callee in self.func.infer(context):
  File "/home/winston/.vscode/extensions/ms-python.pylint-2023.4.0/bundled/libs/astroid/nodes/node_ng.py", line 184, in infer
    for i, result in enumerate(self._infer(context=context, **kwargs)):
  File "/home/winston/.vscode/extensions/ms-python.pylint-2023.4.0/bundled/libs/astroid/decorators.py", line 142, in raise_if_nothing_inferred
    yield next(generator)
          ^^^^^^^^^^^^^^^
  File "/home/winston/.vscode/extensions/ms-python.pylint-2023.4.0/bundled/libs/astroid/decorators.py", line 111, in wrapped
    for res in _func(node, context, **kwargs):
  File "/home/winston/.vscode/extensions/ms-python.pylint-2023.4.0/bundled/libs/astroid/inference.py", line 358, in infer_attribute
    for owner in self.expr.infer(context):
  File "/home/winston/.vscode/extensions/ms-python.pylint-2023.4.0/bundled/libs/astroid/nodes/node_ng.py", line 184, in infer
    for i, result in enumerate(self._infer(context=context, **kwargs)):
  File "/home/winston/.vscode/extensions/ms-python.pylint-2023.4.0/bundled/libs/astroid/decorators.py", line 142, in raise_if_nothing_inferred
    yield next(generator)
          ^^^^^^^^^^^^^^^
  File "/home/winston/.vscode/extensions/ms-python.pylint-2023.4.0/bundled/libs/astroid/decorators.py", line 111, in wrapped
    for res in _func(node, context, **kwargs):
  File "/home/winston/.vscode/extensions/ms-python.pylint-2023.4.0/bundled/libs/astroid/inference.py", line 372, in infer_attribute
    yield from owner.igetattr(self.attrname, context)
  File "/home/winston/.vscode/extensions/ms-python.pylint-2023.4.0/bundled/libs/astroid/nodes/scoped_nodes/scoped_nodes.py", line 2625, in igetattr
    first_scope = first_attr.scope()
                  ^^^^^^^^^^^^^^^^^^
  File "/home/winston/.vscode/extensions/ms-python.pylint-2023.4.0/bundled/libs/astroid/nodes/node_ng.py", line 360, in scope
    raise ParentMissingError(target=self)
astroid.exceptions.ParentMissingError: Parent not found on <Const.str l.None at 0x7fa4e2e221d0>.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/winston/.vscode/extensions/ms-python.pylint-2023.4.0/bundled/libs/pylint/lint/pylinter.py", line 763, in _lint_files
    self._lint_file(fileitem, module, check_astroid_module)
  File "/home/winston/.vscode/extensions/ms-python.pylint-2023.4.0/bundled/libs/pylint/lint/pylinter.py", line 800, in _lint_file
    raise astroid.AstroidError from e
astroid.exceptions.AstroidError
```

### Configuration

```ini
[tool.pylint.format]
good-names = [
    'x', 'y', 'z', 'id'
]

[tool.pylint.messages_control]
disable = [
    'missing-module-docstring',
    'no-name-in-module',
    'useless-import-alias',
    'line-too-long'
]
```

### Command used

```shell
NIL
```

### Pylint output

```json
[
    {
        "type": "fatal",
        "module": "server.models.base",
        "obj": "",
        "line": 1,
        "column": 0,
        "endLine": null,
        "endColumn": null,
        "path": "server/models/base.py",
        "symbol": "astroid-error",
        "message": "/home/winston/projects/admin-llm-chatbot/server/models/base.py: Fatal error while checking '/home/winston/projects/admin-llm-chatbot/server/models/base.py'. Please open an issue in our bug tracker so we address this. There is a pre-filled template that you can use in '/home/winston/.cache/pylint/pylint-crash-2023-04-13-14-03-49.txt'.",
        "message-id": "F0002"
    }
]
```

### Expected behavior

Should not crash.

### Pylint version

```shell
ms-python.pylint-2023.4.0
```

### OS / Environment

Arch Linux

### Additional dependencies

SQLAlchemy == 2.0.9

**Comment by jacobtylerwalls** [comment] 2023-04-13 10:45
Duplicate of #7680

**Closed by jacobtylerwalls** 2023-04-13 10:45 UTC
Labels: Needs triage :inbox_tray:
